In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', 500)

In [3]:
ALL_EVALUATIONS="tests/evaluation_10_retrievers_000_009_sampled_50_queries_gpt-4-1106-preview_20240108.tsv"

BM25_RUN="tests/200-queries-passagens-by-BM25-pt_v2_with_query_id_run.txt"
BM25_E5_RUN="tests/bm25_e5_docs_000_999_50_sampled_queries_run.txt"
BM25_MT5_RUN="tests/200-queries-passagens-by-BM25-mT5_v4_with_query_id_run.txt"
SPLADE_RUN="tests/splade_pt_result_with_clueweb_id_run.txt"
COLBERTX_RUN="tests/colbertx_all_znormalized_validation_scores_000_199_run.txt"
E5_RUN="tests/e5_docs_000_009_50_sampled_queries_score_inv_run.txt"
E5_BASE_RUN="tests/e5_base_docs_000_009_50_sampled_queries_score_inv_run.txt"
BM25_1M_RUN="tests/bm25_1M_docs_000_009_sampled_50_queries_run.txt"
BM25_1M_MASSIVEWEB_RUN="tests/bm25_massiveweb_1M_docs_000_009_sampled_50_queries_run.txt"

In [4]:
SPLADE_MT5="tests/splade_mt5_docs_000_009_50_sampled_queries.tsv"

In [5]:
retrievers_results = []

### Format GPT-4 evaluations to qrels format

In [6]:
eval_df = pd.read_csv(ALL_EVALUATIONS, sep='\t')

In [7]:
eval_df

query_id                                                  query  \
0            1       Qual a maior característica da fauna brasileira?   
1            1       Qual a maior característica da fauna brasileira?   
2            1       Qual a maior característica da fauna brasileira?   
3            1       Qual a maior característica da fauna brasileira?   
4            1       Qual a maior característica da fauna brasileira?   
...        ...                                                    ...   
3062       199  Quais foram os principais artistas do Impressionismo?   
3063       199  Quais foram os principais artistas do Impressionismo?   
3064       199  Quais foram os principais artistas do Impressionismo?   
3065       199  Quais foram os principais artistas do Impressionismo?   
3066       199  Quais foram os principais artistas do Impressionismo?   

                        passage_id    mT5  splade  colbertx  bm25_e5   bm25  \
0      clueweb22-pt0000-82-13187_0  False   False      True    False  False   
1      clueweb22-pt0000-59-04599_2  False   False      True    False  False   
2     clueweb22-pt0000-64-06285_39   True    True     False    False  False   
3      clueweb22-pt0000-77-06884_1  False    True      True    False  False   
4      clueweb22-pt0000-78-09747_0   True   False     False    False   True   
...                            ...    ...     ...       ...      ...    ...   
3062   clueweb22-pt0002-04-01418_0  False   False     False    False  False   
3063   clueweb22-pt0001-24-17228_0  False   False     False    False  False   
3064   clueweb22-pt0000-08-07683_2  False   False     False    False  False   
3065   clueweb22-pt0000-86-08729_0  False   False     False    False  False   
3066   clueweb22-pt0002-03-16683_4  False   False     False    False  False   

         e5  e5_base  bm25_1M  bm25_1M_massiveweb  splade_mT5  \
0     False    False    False               False       False   
1     False    False    False               False       False   
2     False     True    False               False       False   
3     False    False    False               False        True   
4     False    False    False                True        True   
...     ...      ...      ...                 ...         ...   
3062  False    False    False                True       False   
3063  False    False    False                True       False   
3064  False    False    False                True       False   
3065  False    False    False                True       False   
3066  False    False    False               False        True   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    passage  \
0                                                                                                       

In [8]:
eval_df.drop_duplicates("query_id")[['query_id', 'query']]

query_id  \
0            1   
64           2   
135          9   
200         11   
255         13   
309         15   
353         17   
404         20   
481         21   
554         22   
613         24   
687         26   
744         28   
814         47   
892         49   
951         51   
1000        54   
1059        60   
1108        62   
1184        64   
1237        68   
1316        84   
1373        95   
1445        98   
1510       105   
1575       113   
1626       115   
1689       117   
1763       126   
1847       127   
1882       128   
1931       136   
1993       147   
2059       152   
2121       153   
2186       154   
2233       160   
2284       161   
2330       163   
2383       167   
2463       170   
2530       172   
2582       180   
2634       181   
2705       182   
2762       189   
2828       193   
2887       195   
2938       196   
3007       199   

                                                                                           query  
0                                               Qual a maior característica da fauna brasileira?  
64                              Por que os países Guiana e Suriname não são filiados a Conmebol?  
135                                           quais países europeus seguem o regime monarquista?  
200      quais os critérios de definição dos monumentos intitulados maravilhas do mundo moderno?  
255                                 Como o Brasil reagiu a epidemia de AIDS no fim do século XX?  
309                                                   Qual a maior torcida de futebol do Brasil?  
353           Quando se realizou o plebiscito popular para definir o sistema político do Brasil?  
404                                            Por que a legislação de um país é tão importante?  
481                                                       Qual o nosso atual sistema de governo?  
554                                                  Qual o sistema de governo da África do Sul?  
613                                                          Por que dividir um país em estados?  
687                                                Como podemos classificar o relevo brasileiro?  
744                                                Existem vantagens ao definir uma moeda única?  
814                                     Como transformar uma cidade pacata em um polo turístico?  
892                                         Quais são os melhores parques nacionais de Portugal?  
951                                                  Qual a melhor cidade para ficar no Jalapão?  
1000                                                              Quais são os biomas do Brasil?  
1059                           Quando foi criada a consolidação das leis trabalhistas no brasil?  
1108                                Quais partidos já ocuparam o cargo da presidência do Brasil?  
1184                           Por que os anos de 80 são considerados a década perdida no Brasil  
1237                                   Quais são os principais intérpretes da música brasileira?  
1316                                           Qual é a principal cidade do basquete brasileiro?  
1373                                        É possível conhecer o Pico da Bandeira com crianças?  
1445                                   Qual o critério para classificação para a Copa do Brasil?  
1510                                                Onde está localizada a Praça XV de Novembro?  
1575                                                        Fatores de risco para cancer de pele  
1626                                                 Cuidados ao usar materiais perfurocortantes  
1689                                                                   Delirio versus alucinação  
1763                                     Quantas placas são formadas pelos materiais condutores?  
1847                                              O que é a associação em série de um capacitor?  
1882              

#### Check scores distribution on the current qrels

In [9]:
np.unique(eval_df['score'].to_numpy(), return_counts=True)

(array([0, 1, 2, 3]), array([1465,  613,  474,  515]))

In [10]:
for group_name, group_df in eval_df.groupby('query_id'):
    print("\nquery_id={}".format(group_name))
    
    print(np.unique(group_df['score'].to_numpy(), return_counts=True))


query_id=1
(array([0, 1, 2, 3]), array([ 9, 35, 12,  8]))

query_id=2
(array([0, 1, 2, 3]), array([66,  2,  1,  2]))

query_id=9
(array([0, 1, 2, 3]), array([45,  6,  9,  5]))

query_id=11
(array([0, 1, 2, 3]), array([33, 12,  8,  2]))

query_id=13
(array([0, 1, 2, 3]), array([25, 10, 15,  4]))

query_id=15
(array([0, 1, 2, 3]), array([16, 14,  1, 13]))

query_id=17
(array([0, 1, 2, 3]), array([15,  7,  1, 28]))

query_id=20
(array([0, 1, 2, 3]), array([13, 39, 19,  6]))

query_id=21
(array([0, 1, 2, 3]), array([38, 18,  2, 15]))

query_id=22
(array([0, 1, 2, 3]), array([42, 10,  1,  6]))

query_id=24
(array([0, 1, 2, 3]), array([45, 17, 10,  2]))

query_id=26
(array([0, 1, 2, 3]), array([13,  8,  9, 27]))

query_id=28
(array([0, 1, 2, 3]), array([42, 11, 13,  4]))

query_id=47
(array([0, 1, 2]), array([35, 24, 19]))

query_id=49
(array([0, 1, 2, 3]), array([20, 20, 18,  1]))

query_id=51
(array([0, 1, 2, 3]), array([21, 17, 10,  1]))

query_id=54
(array([0, 1, 2, 3]), array([ 1, 12, 

In [11]:
eval_df.groupby('query_id').count()

query  passage_id  mT5  splade  colbertx  bm25_e5  bm25  e5  \
query_id                                                                
1            64          64   64      64        64       64    64  64   
2            71          71   71      71        71       71    71  71   
9            65          65   65      65        65       65    65  65   
11           55          55   55      55        55       55    55  55   
13           54          54   54      54        54       54    54  54   
15           44          44   44      44        44       44    44  44   
17           51          51   51      51        51       51    51  51   
20           77          77   77      77        77       77    77  77   
21           73          73   73      73        73       73    73  73   
22           59          59   59      59        59       59    59  59   
24           74          74   74      74        74       74    74  74   
26           57          57   57      57        57       57    57  57   
28           70          70   70      70        70       70    70  70   
47           78          78   78      78        78       78    78  78   
49           59          59   59      59        59       59    59  59   
51           49          49   49      49        49       49    49  49   
54           59          59   59      59        59       59    59  59   
60           49          49   49      49        49       49    49  49   
62           76          76   76      76        76       76    76  76   
64           53          53   53      53        53       53    53  53   
68           79          79   79      79        79       79    79  79   
84           57          57   57      57        57       57    57  57   
95           72          72   72      72        72       72    72  72   
98           65          65   65      65        65       65    65  65   
105          65          65   65      65        65       65    65  65   
113          51          51   51      51        51       51    51  51   
115          63          63   63      63        63       63    63  63   
117          74          74   74      74        74       74    74  74   
126          84          84   84      84        84       84    84  84   
127          35          35   35      35        35       35    35  35   
128          49          49   49      49        49       49    49  49   
136          62          62   62      62        62       62    62  62   
147          66          66   66      66        66       66    66  66   
152          62          62   62      62        62       62    62  62   
153          65          65   65      65        65       65    65  65   
154          47          47   47      47        47       47    47  47   
160          51          51   51      51        51       51    51  51   
161          46          46   46      46        46       46    46  46   
163          53          53   53      53        53       53    53  53   
167          80          80   80      80        80       80    80  80   
170          67          67   67      67        67       67    67  67   
172          52          52   52      52        52       52    52  52   
180          52          52   52      52        52       52    52  52   
181          71          71   71      71        71       71    71  71   
182          57          57   57      57        57       57    57  57   
189          66          66   66      66        66       66    66  66   
193          59          59   59      59        59       59    59  59   
195          51          51   51      51        51       51    51  51   
196          69          69   69      69        69       69    69  69   
199          60          60   60      60        60       60    60  60   

          e5_base  bm25_1M  bm25_1M_massiveweb  splade_mT5  passage  score  \
query_id                                                                     
1              64       64                  64          6

In [12]:
eval_df.groupby('query_id').count()['query'].describe()

count    50.000000
mean     61.340000
std      10.831944
min      35.000000
25%      52.250000
50%      61.000000
75%      69.750000
max      84.000000
Name: query, dtype: float64

#### Prepare the qrels format for trec_eval tools

In [13]:
eval_df['0'] = '0'

In [14]:
qrels_filename = os.path.join(os.path.dirname(ALL_EVALUATIONS), "{}_qrel.txt".format(os.path.splitext(os.path.basename(ALL_EVALUATIONS))[0]))

In [15]:
qrels_filename

'tests/evaluation_10_retrievers_000_009_sampled_50_queries_gpt-4-1106-preview_20240108_qrel.txt'

In [16]:
eval_df.sort_values('query_id')[['query_id', '0', 'passage_id', 'score']].to_csv(qrels_filename, header=None, index=False, sep=" ")

### Compute BM25 nDCG@10

In [17]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    {qrels_filename} tests/200-queries-passagens-by-BM25-pt_v2_with_query_id_run.txt

In [18]:
retrievers_results.append({'retriever':'BM25', 'nDCG@10': result[0].split('\t')[-1]})

In [19]:
retrievers_results

[{'retriever': 'BM25', 'nDCG@10': '0.4546'}]

### Compute BM25 + E5 nDCG@10

In [20]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    {qrels_filename} {BM25_E5_RUN}

In [21]:
retrievers_results.append({'retriever':'BM25+E5', 'nDCG@10': result[0].split('\t')[-1]})

### Compute BM25 + mT5 nDCG@10

In [22]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    {qrels_filename} {BM25_MT5_RUN}

In [23]:
retrievers_results.append({'retriever':'BM25+mT5', 'nDCG@10': result[0].split('\t')[-1]})

### Compute SPLADE nDCG@10

In [24]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    {qrels_filename} {SPLADE_RUN}

In [25]:
retrievers_results.append({'retriever':'SPLADE_pt-BR', 'nDCG@10': result[0].split('\t')[-1]})

### Compute ColBERTX nDCG@10

In [26]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    {qrels_filename} {COLBERTX_RUN}

In [27]:
retrievers_results.append({'retriever':'ColBERT-X_mMARCO_pt-BR', 'nDCG@10': result[0].split('\t')[-1]})

### Compute E5 nDCG@10

In [28]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    {qrels_filename} {E5_RUN}

In [29]:
retrievers_results.append({'retriever':'E5', 'nDCG@10': result[0].split('\t')[-1]})

### Compute E5 base nDCG@10

In [30]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    {qrels_filename} {E5_BASE_RUN}

In [31]:
retrievers_results.append({'retriever':'E5 base', 'nDCG@10': result[0].split('\t')[-1]})

### Compute BM25 1M nDCG@10

In [32]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    {qrels_filename} {BM25_1M_RUN}

retrievers_results.append({'retriever':'BM25 1M', 'nDCG@10': result[0].split('\t')[-1]})

### Compute BM25 1M massiveweb filtered nDCG@10

In [33]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    {qrels_filename} {BM25_1M_MASSIVEWEB_RUN}

retrievers_results.append({'retriever':'BM25 1M massiveweb', 'nDCG@10': result[0].split('\t')[-1]})

### Prepare SPLADE + mT5 retrieval results in run format

In [34]:
splade_mt5_df = pd.read_csv(SPLADE_MT5, sep="\t")

In [35]:
splade_mt5_df.groupby("query_id").head(10).count()

query          500
passage_id     500
score          500
query_id       500
colbertx_id    500
passage        500
dtype: int64

In [36]:
splade_mt5_df

query  \
0                                              Qual a maior característica da fauna brasileira?   
1                                              Qual a maior característica da fauna brasileira?   
2                                              Qual a maior característica da fauna brasileira?   
3                                              Qual a maior característica da fauna brasileira?   
4                                              Qual a maior característica da fauna brasileira?   
5                                              Qual a maior característica da fauna brasileira?   
6                                              Qual a maior característica da fauna brasileira?   
7                                              Qual a maior característica da fauna brasileira?   
8                                              Qual a maior característica da fauna brasileira?   
9                                              Qual a maior característica da fauna brasileira?   
10                             Por que os países Guiana e Suriname não são filiados a Conmebol?   
11                             Por que os países Guiana e Suriname não são filiados a Conmebol?   
12                             Por que os países Guiana e Suriname não são filiados a Conmebol?   
13                             Por que os países Guiana e Suriname não são filiados a Conmebol?   
14                             Por que os países Guiana e Suriname não são filiados a Conmebol?   
15                             Por que os países Guiana e Suriname não são filiados a Conmebol?   
16                             Por que os países Guiana e Suriname não são filiados a Conmebol?   
17                             Por que os países Guiana e Suriname não são filiados a Conmebol?   
18                             Por que os países Guiana e Suriname não são filiados a Conmebol?   
19                             Por que os países Guiana e Suriname não são filiados a Conmebol?   
20                                           quais países europeus seguem o regime monarquista?   
21                                           quais países europeus seguem o regime monarquista?   
22                                           quais países europeus seguem o regime monarquista?   
23                                           quais países europeus seguem o regime monarquista?   
24                                           quais países europeus seguem o regime monarquista?   
25                                           quais países europeus seguem o regime monarquista?   
26                                           quais países europeus seguem o regime monarquista?   
27                                           quais países europeus seguem o regime monarquista?   
28                                           quais países europeus seguem o regime monarquista?   
29                                           quais países europeus seguem o regime monarquista?   
30      quais os critérios de definição dos monumentos intitulados maravilhas do mundo moderno?   
31      quais os critérios de definição dos monumentos intitulados maravilhas do mundo moderno?   
32      quais os critérios de definição dos monumentos intitulados maravilhas do mundo moderno?   
33      quais os critérios de definição dos monumentos intitulados maravilhas do mundo moderno?   
34      quais os critérios de definição dos monumentos intitulados maravilhas do mundo moderno?   
35      quais os critérios de definição dos monumentos intitulados maravilhas do mundo moderno?   
36      quais os critérios de definição dos monumentos intitulados maravilhas do mundo moderno?   
37      quais os critérios de definição dos monumentos intitulados maravilhas do mundo moderno?   
38      quais os critérios de definição dos monumentos intitulados maravilhas do mundo moderno?   
39      quais os critérios de definição dos monumentos intitulados maravilhas do mundo moderno?   
40                             

In [37]:
splade_mt5_run_df = splade_mt5_df.sort_values(["query_id", "score"], ascending=[True, False]).groupby("query_id").head(10)

In [38]:
splade_mt5_run_df.shape

(500, 6)

In [39]:
splade_mt5_run_df['Q0'] = "Q0"
splade_mt5_run_df['comment'] = "gpt-4-1106-preview"
splade_mt5_run_df['index'] = np.tile(list(range(1, 11)), 50)

In [40]:
splade_mt5_run_df.head(12)

query  \
0                   Qual a maior característica da fauna brasileira?   
1                   Qual a maior característica da fauna brasileira?   
2                   Qual a maior característica da fauna brasileira?   
3                   Qual a maior característica da fauna brasileira?   
4                   Qual a maior característica da fauna brasileira?   
5                   Qual a maior característica da fauna brasileira?   
6                   Qual a maior característica da fauna brasileira?   
7                   Qual a maior característica da fauna brasileira?   
8                   Qual a maior característica da fauna brasileira?   
9                   Qual a maior característica da fauna brasileira?   
10  Por que os países Guiana e Suriname não são filiados a Conmebol?   
11  Por que os países Guiana e Suriname não são filiados a Conmebol?   

                       passage_id  score  query_id  colbertx_id  \
0     clueweb22-pt0001-22-15255_0   1000         1      5877599   
1    clueweb22-pt0000-61-07564_63    990         1      2899447   
2    clueweb22-pt0000-21-03309_40    980         1      1021792   
3     clueweb22-pt0000-77-06884_1    970         1      3668516   
4     clueweb22-pt0000-17-01771_1    960         1       827050   
5     clueweb22-pt0001-35-10105_3    950         1      6490561   
6     clueweb22-pt0000-78-09747_0    940         1      3718313   
7    clueweb22-pt0001-46-05303_17    930         1      7028401   
8   clueweb22-pt0001-98-02862_292    920         1      9445537   
9     clueweb22-pt0001-20-06522_1    910         1      5762187   
10    clueweb22-pt0001-73-10674_5   1000         2      8315740   
11    clueweb22-pt0001-87-10897_2    990         2      8946033   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         passage  \
0                                                                                                                                                                                                      Fauna do Brasil - Toda Matéria Biologia › Zoologia Fauna do Brasil A fauna do Brasil é provavelmente a que possui a maior diversidade em espécies de animais vertebrados, anfíbios e primatas do globo terrestre. Existem três vezes mais espécies de peixes de água doce no Brasil do que em qualquer lugar no mundo. As aves também são muito variadas, colocando o Brasil como o país com a maior variedade de espécies na América do Sul e o terceiro do mundo em espécies de mamíferos. De igual modo, a Floresta Atlântica está entre as cinco regiões do planeta com mais espécies nativas, das quais 17% são aves e 10% são anfíbios e mamíferos encontrados somente na fauna brasileira. Vale citar que os

In [41]:
splade_mt5_run_df[['query_id', 'Q0', "passage_id", "index", "score", "comment"]].to_csv("tests/splade_mt5_docs_000_009_50_sampled_queries_run.txt", 
                                                                                        header=None, index=False, sep=" ")

#### Compute SPLADE + mT5 NDCG@10

In [42]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    {qrels_filename} "tests/splade_mt5_docs_000_009_50_sampled_queries_run.txt"

In [43]:
retrievers_results.append({'retriever':'SPLADE + mT5', 'nDCG@10': result[0].split('\t')[-1]})

### Check the overall results

In [44]:
pd.DataFrame(retrievers_results)

retriever nDCG@10
0                    BM25  0.4546
1                 BM25+E5  0.6486
2                BM25+mT5  0.7249
3            SPLADE_pt-BR  0.5900
4  ColBERT-X_mMARCO_pt-BR  0.6394
5                      E5  0.5672
6                 E5 base  0.4063
7                 BM25 1M  0.3234
8      BM25 1M massiveweb  0.3203
9            SPLADE + mT5  0.7107