In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', 500)

In [3]:
ALL_EVALUATIONS="tests/evaluation_07_retrievers_000_009_sampled_50_queries_gpt-4-1106-preview_20231220.tsv"

BM25_RUN="tests/200-queries-passagens-by-BM25-pt_v2_with_query_id_run.txt"
BM25_E5_RUN="tests/bm25_e5_docs_000_999_50_sampled_queries_run.txt"
BM25_MT5_RUN="tests/200-queries-passagens-by-BM25-mT5_v4_with_query_id_run.txt"
SPLADE_RUN="tests/splade_pt_result_with_clueweb_id_run.txt"
COLBERTX_RUN="tests/colbertx_all_znormalized_validation_scores_000_199_run.txt"
E5_RUN="tests/e5_docs_000_009_50_sampled_queries_score_inv_run.txt"

In [33]:
E5_BASE="tests/e5_base_docs_000_009_50_sampled_queries.tsv"

In [5]:
retrievers_results = []

### Format GPT-4 evaluations to qrels format

In [6]:
eval_df = pd.read_csv(ALL_EVALUATIONS, sep='\t')

In [7]:
eval_df

query_id                                                  query  \
0            1       Qual a maior característica da fauna brasileira?   
1            1       Qual a maior característica da fauna brasileira?   
2            1       Qual a maior característica da fauna brasileira?   
3            1       Qual a maior característica da fauna brasileira?   
4            1       Qual a maior característica da fauna brasileira?   
...        ...                                                    ...   
2187       199  Quais foram os principais artistas do Impressionismo?   
2188       199  Quais foram os principais artistas do Impressionismo?   
2189       199  Quais foram os principais artistas do Impressionismo?   
2190       199  Quais foram os principais artistas do Impressionismo?   
2191       199  Quais foram os principais artistas do Impressionismo?   

                        passage_id    mT5  splade  colbertx  bm25_e5   bm25  \
0      clueweb22-pt0000-82-13187_0  False   False      True    False  False   
1      clueweb22-pt0000-59-04599_2  False   False      True    False  False   
2     clueweb22-pt0000-64-06285_39   True    True     False    False  False   
3      clueweb22-pt0000-77-06884_1  False    True      True    False  False   
4      clueweb22-pt0000-78-09747_0   True   False     False    False   True   
...                            ...    ...     ...       ...      ...    ...   
2187   clueweb22-pt0001-30-11307_0  False   False     False    False  False   
2188   clueweb22-pt0000-79-06140_4  False   False     False    False  False   
2189   clueweb22-pt0001-94-07405_5  False   False     False    False  False   
2190   clueweb22-pt0000-50-08513_6  False   False     False    False  False   
2191   clueweb22-pt0000-42-00056_5  False   False     False    False  False   

         e5 e5_base  \
0     False   False   
1     False   False   
2     False    True   
3     False   False   
4     False   False   
...     ...     ...   
2187   True    True   
2188   True   False   
2189  False     NaN   
2190  False     NaN   
2191  False     NaN   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     passage  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Mamíferos do Brasil - Zoologia | Museu Nacional - UFRJ ➤ Início ➤ Exposições ➤ Zoologia (Acervo) ➤ In

In [8]:
eval_df.drop_duplicates("query_id")[['query_id', 'query']]

query_id  \
0            1   
44           2   
96           9   
140         11   
181         13   
219         15   
244         17   
278         20   
336         21   
390         22   
431         24   
486         26   
526         28   
576         47   
634         49   
675         51   
709         54   
750         60   
786         62   
841         64   
879         68   
936         84   
979         95   
1035        98   
1081       105   
1130       113   
1164       115   
1205       117   
1260       126   
1320       127   
1341       128   
1369       136   
1416       147   
1457       152   
1504       153   
1551       154   
1589       160   
1626       161   
1658       163   
1700       167   
1758       170   
1805       172   
1840       180   
1882       181   
1936       182   
1973       189   
2019       193   
2063       195   
2098       196   
2150       199   

                                                                                           query  
0                                               Qual a maior característica da fauna brasileira?  
44                              Por que os países Guiana e Suriname não são filiados a Conmebol?  
96                                            quais países europeus seguem o regime monarquista?  
140      quais os critérios de definição dos monumentos intitulados maravilhas do mundo moderno?  
181                                 Como o Brasil reagiu a epidemia de AIDS no fim do século XX?  
219                                                   Qual a maior torcida de futebol do Brasil?  
244           Quando se realizou o plebiscito popular para definir o sistema político do Brasil?  
278                                            Por que a legislação de um país é tão importante?  
336                                                       Qual o nosso atual sistema de governo?  
390                                                  Qual o sistema de governo da África do Sul?  
431                                                          Por que dividir um país em estados?  
486                                                Como podemos classificar o relevo brasileiro?  
526                                                Existem vantagens ao definir uma moeda única?  
576                                     Como transformar uma cidade pacata em um polo turístico?  
634                                         Quais são os melhores parques nacionais de Portugal?  
675                                                  Qual a melhor cidade para ficar no Jalapão?  
709                                                               Quais são os biomas do Brasil?  
750                            Quando foi criada a consolidação das leis trabalhistas no brasil?  
786                                 Quais partidos já ocuparam o cargo da presidência do Brasil?  
841                            Por que os anos de 80 são considerados a década perdida no Brasil  
879                                    Quais são os principais intérpretes da música brasileira?  
936                                            Qual é a principal cidade do basquete brasileiro?  
979                                         É possível conhecer o Pico da Bandeira com crianças?  
1035                                   Qual o critério para classificação para a Copa do Brasil?  
1081                                                Onde está localizada a Praça XV de Novembro?  
1130                                                        Fatores de risco para cancer de pele  
1164                                                 Cuidados ao usar materiais perfurocortantes  
1205                                                                   Delirio versus alucinação  
1260                                     Quantas placas são formadas pelos materiais condutores?  
1320                                              O que é a associação em série de um capacitor?  
1341              

#### Check scores distribution on the current qrels

In [9]:
np.unique(eval_df['score'].to_numpy(), return_counts=True)

(array([0, 1, 2, 3]), array([946, 432, 379, 435]))

In [10]:
for group_name, group_df in eval_df.groupby('query_id'):
    print("\nquery_id={}".format(group_name))
    
    print(np.unique(group_df['score'].to_numpy(), return_counts=True))


query_id=1
(array([0, 1, 2, 3]), array([ 5, 21, 11,  7]))

query_id=2
(array([0, 1, 2, 3]), array([47,  2,  1,  2]))

query_id=9
(array([0, 1, 2, 3]), array([26,  4,  9,  5]))

query_id=11
(array([0, 1, 2, 3]), array([24,  8,  7,  2]))

query_id=13
(array([0, 1, 2, 3]), array([15,  8, 11,  4]))

query_id=15
(array([0, 1, 2, 3]), array([ 2, 10,  1, 12]))

query_id=17
(array([0, 1, 2, 3]), array([ 6,  2,  1, 25]))

query_id=20
(array([0, 1, 2, 3]), array([ 5, 31, 18,  4]))

query_id=21
(array([0, 1, 2, 3]), array([24, 15,  1, 14]))

query_id=22
(array([0, 1, 3]), array([29,  7,  5]))

query_id=24
(array([0, 1, 2, 3]), array([27, 17,  9,  2]))

query_id=26
(array([0, 1, 2, 3]), array([11,  2,  7, 20]))

query_id=28
(array([0, 1, 2, 3]), array([26,  7, 13,  4]))

query_id=47
(array([0, 1, 2]), array([25, 18, 15]))

query_id=49
(array([0, 1, 2, 3]), array([13, 14, 13,  1]))

query_id=51
(array([0, 1, 2, 3]), array([14, 13,  6,  1]))

query_id=54
(array([1, 2, 3]), array([ 7,  7, 27]))

que

In [11]:
eval_df.groupby('query_id').count()

query  passage_id  mT5  splade  colbertx  bm25_e5  bm25  e5  \
query_id                                                                
1            44          44   44      44        44       44    44  44   
2            52          52   52      52        52       52    52  52   
9            44          44   44      44        44       44    44  44   
11           41          41   41      41        41       41    41  41   
13           38          38   38      38        38       38    38  38   
15           25          25   25      25        25       25    25  25   
17           34          34   34      34        34       34    34  34   
20           58          58   58      58        58       58    58  58   
21           54          54   54      54        54       54    54  54   
22           41          41   41      41        41       41    41  41   
24           55          55   55      55        55       55    55  55   
26           40          40   40      40        40       40    40  40   
28           50          50   50      50        50       50    50  50   
47           58          58   58      58        58       58    58  58   
49           41          41   41      41        41       41    41  41   
51           34          34   34      34        34       34    34  34   
54           41          41   41      41        41       41    41  41   
60           36          36   36      36        36       36    36  36   
62           55          55   55      55        55       55    55  55   
64           38          38   38      38        38       38    38  38   
68           57          57   57      57        57       57    57  57   
84           43          43   43      43        43       43    43  43   
95           56          56   56      56        56       56    56  56   
98           46          46   46      46        46       46    46  46   
105          49          49   49      49        49       49    49  49   
113          34          34   34      34        34       34    34  34   
115          41          41   41      41        41       41    41  41   
117          55          55   55      55        55       55    55  55   
126          60          60   60      60        60       60    60  60   
127          21          21   21      21        21       21    21  21   
128          28          28   28      28        28       28    28  28   
136          47          47   47      47        47       47    47  47   
147          41          41   41      41        41       41    41  41   
152          47          47   47      47        47       47    47  47   
153          47          47   47      47        47       47    47  47   
154          38          38   38      38        38       38    38  38   
160          37          37   37      37        37       37    37  37   
161          32          32   32      32        32       32    32  32   
163          42          42   42      42        42       42    42  42   
167          58          58   58      58        58       58    58  58   
170          47          47   47      47        47       47    47  47   
172          35          35   35      35        35       35    35  35   
180          42          42   42      42        42       42    42  42   
181          54          54   54      54        54       54    54  54   
182          37          37   37      37        37       37    37  37   
189          46          46   46      46        46       46    46  46   
193          44          44   44      44        44       44    44  44   
195          35          35   35      35        35       35    35  35   
196          52          52   52      52        52       52    52  52   
199          42          42   42      42        42       42    42  42   

          e5_base  passage  score  reasoning  usage  cost  duration  \
query_id                                                              
1              39       44     44         44     44    44        44   


#### Prepare the qrels format for trec_eval tools

In [12]:
eval_df['0'] = '0'

In [13]:
qrels_filename = os.path.join(os.path.dirname(ALL_EVALUATIONS), "{}_qrel.txt".format(os.path.splitext(os.path.basename(ALL_EVALUATIONS))[0]))

In [14]:
qrels_filename

'tests/evaluation_07_retrievers_000_009_sampled_50_queries_gpt-4-1106-preview_20231220_qrel.txt'

In [15]:
eval_df.sort_values('query_id')[['query_id', '0', 'passage_id', 'score']].to_csv(qrels_filename, header=None, index=False, sep=" ")

### Compute BM25 nDCG@10

In [16]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    {qrels_filename} tests/200-queries-passagens-by-BM25-pt_v2_with_query_id_run.txt

In [17]:
retrievers_results.append({'retriever':'BM25', 'nDCG@10': result[0].split('\t')[-1]})

In [18]:
retrievers_results

[{'retriever': 'BM25', 'nDCG@10': '0.4624'}]

### Compute BM25 + E5 nDCG@10

In [19]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    {qrels_filename} {BM25_E5_RUN}

In [20]:
retrievers_results.append({'retriever':'BM25+E5', 'nDCG@10': result[0].split('\t')[-1]})

### Compute BM25 + mT5 nDCG@10

In [21]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    {qrels_filename} {BM25_MT5_RUN}

In [22]:
retrievers_results.append({'retriever':'BM25+mT5', 'nDCG@10': result[0].split('\t')[-1]})

### Compute SPLADE nDCG@10

In [23]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    {qrels_filename} {SPLADE_RUN}

In [24]:
retrievers_results.append({'retriever':'SPLADE_pt-BR', 'nDCG@10': result[0].split('\t')[-1]})

### Compute ColBERTX nDCG@10

In [25]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    {qrels_filename} {COLBERTX_RUN}

In [26]:
retrievers_results.append({'retriever':'ColBERT-X_mMARCO_pt-BR', 'nDCG@10': result[0].split('\t')[-1]})

### Compute E5 nDCG@10

In [27]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    {qrels_filename} {E5_RUN}

In [28]:
retrievers_results.append({'retriever':'E5', 'nDCG@10': result[0].split('\t')[-1]})

### Prepare E5 base retrieval results in run format

In [34]:
e5_df = pd.read_csv(E5_BASE, sep="\t")

In [35]:
e5_df.groupby("query_id").head(10).count()

query          500
passage_id     500
score          500
query_id       500
score_inv      500
colbertx_id    500
passage        500
dtype: int64

In [36]:
e5_df

query  \
0                                              Qual a maior característica da fauna brasileira?   
1                                              Qual a maior característica da fauna brasileira?   
2                                              Qual a maior característica da fauna brasileira?   
3                                              Qual a maior característica da fauna brasileira?   
4                                              Qual a maior característica da fauna brasileira?   
5                                              Qual a maior característica da fauna brasileira?   
6                                              Qual a maior característica da fauna brasileira?   
7                                              Qual a maior característica da fauna brasileira?   
8                                              Qual a maior característica da fauna brasileira?   
9                                              Qual a maior característica da fauna brasileira?   
10                             Por que os países Guiana e Suriname não são filiados a Conmebol?   
11                             Por que os países Guiana e Suriname não são filiados a Conmebol?   
12                             Por que os países Guiana e Suriname não são filiados a Conmebol?   
13                             Por que os países Guiana e Suriname não são filiados a Conmebol?   
14                             Por que os países Guiana e Suriname não são filiados a Conmebol?   
15                             Por que os países Guiana e Suriname não são filiados a Conmebol?   
16                             Por que os países Guiana e Suriname não são filiados a Conmebol?   
17                             Por que os países Guiana e Suriname não são filiados a Conmebol?   
18                             Por que os países Guiana e Suriname não são filiados a Conmebol?   
19                             Por que os países Guiana e Suriname não são filiados a Conmebol?   
20                                           quais países europeus seguem o regime monarquista?   
21                                           quais países europeus seguem o regime monarquista?   
22                                           quais países europeus seguem o regime monarquista?   
23                                           quais países europeus seguem o regime monarquista?   
24                                           quais países europeus seguem o regime monarquista?   
25                                           quais países europeus seguem o regime monarquista?   
26                                           quais países europeus seguem o regime monarquista?   
27                                           quais países europeus seguem o regime monarquista?   
28                                           quais países europeus seguem o regime monarquista?   
29                                           quais países europeus seguem o regime monarquista?   
30      quais os critérios de definição dos monumentos intitulados maravilhas do mundo moderno?   
31      quais os critérios de definição dos monumentos intitulados maravilhas do mundo moderno?   
32      quais os critérios de definição dos monumentos intitulados maravilhas do mundo moderno?   
33      quais os critérios de definição dos monumentos intitulados maravilhas do mundo moderno?   
34      quais os critérios de definição dos monumentos intitulados maravilhas do mundo moderno?   
35      quais os critérios de definição dos monumentos intitulados maravilhas do mundo moderno?   
36      quais os critérios de definição dos monumentos intitulados maravilhas do mundo moderno?   
37      quais os critérios de definição dos monumentos intitulados maravilhas do mundo moderno?   
38      quais os critérios de definição dos monumentos intitulados maravilhas do mundo moderno?   
39      quais os critérios de definição dos monumentos intitulados maravilhas do mundo moderno?   
40                             

In [37]:
e5_run_df = e5_df.sort_values(["query_id", "score_inv"], ascending=[True, False]).groupby("query_id").head(10)

In [38]:
e5_run_df.shape

(500, 7)

In [39]:
e5_run_df['Q0'] = "Q0"
e5_run_df['comment'] = "gpt-4-1106-preview"
e5_run_df['index'] = np.tile(list(range(1, 11)), 50)

In [40]:
e5_run_df.head(12)

query  \
0                   Qual a maior característica da fauna brasileira?   
1                   Qual a maior característica da fauna brasileira?   
2                   Qual a maior característica da fauna brasileira?   
3                   Qual a maior característica da fauna brasileira?   
4                   Qual a maior característica da fauna brasileira?   
5                   Qual a maior característica da fauna brasileira?   
6                   Qual a maior característica da fauna brasileira?   
7                   Qual a maior característica da fauna brasileira?   
8                   Qual a maior característica da fauna brasileira?   
9                   Qual a maior característica da fauna brasileira?   
10  Por que os países Guiana e Suriname não são filiados a Conmebol?   
11  Por que os países Guiana e Suriname não são filiados a Conmebol?   

                       passage_id     score  query_id  score_inv  colbertx_id  \
0     clueweb22-pt0001-22-15255_0  0.122909         1   0.877091      5877599   
1     clueweb22-pt0000-96-00412_0  0.129059         1   0.870941      4583617   
2     clueweb22-pt0001-90-10791_1  0.137393         1   0.862607      9091797   
3     clueweb22-pt0000-77-06884_0  0.138782         1   0.861218      3668515   
4   clueweb22-pt0000-29-05546_422  0.139163         1   0.860837      1402397   
5     clueweb22-pt0000-55-02859_0  0.140847         1   0.859153      2605802   
6     clueweb22-pt0001-70-06195_8  0.142035         1   0.857965      8157162   
7    clueweb22-pt0000-64-06285_39  0.142455         1   0.857545      3048261   
8     clueweb22-pt0000-11-00619_4  0.142769         1   0.857231       528312   
9    clueweb22-pt0000-17-01771_19  0.142988         1   0.857012       827062   
10    clueweb22-pt0000-90-01528_5  0.155220         2   0.844780      4301531   
11   clueweb22-pt0001-93-07977_12  0.160440         2   0.839560      9226136   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             passage  \
0                                                                                                                                                                                                                                          Fauna do Brasil - Toda Matéria Biologia › Zoologia Fauna do Brasil A fauna do Brasil é provavelmente a que possui a maior diversidade em espécies de animais vertebrados, anfíbios e primatas do globo terrestre. Existem três vezes mais espécies de peixes de água doce no Brasil do que em qualquer lugar no mundo. As aves também são muito variadas, colocando o Brasil como o país com a maior variedade de espécies na América do Sul e o terc

In [41]:
e5_run_df[['query_id', 'Q0', "passage_id", "index", "score_inv", "comment"]].to_csv("tests/e5_base_docs_000_009_50_sampled_queries_score_inv_run.txt", 
                                                                                    header=None, index=False, sep=" ")

#### Compute E5 NDCG@10

In [42]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    {qrels_filename} "tests/e5_base_docs_000_009_50_sampled_queries_score_inv_run.txt"

In [43]:
retrievers_results.append({'retriever':'E5 base', 'nDCG@10': result[0].split('\t')[-1]})

### Check the overall results

In [44]:
pd.DataFrame(retrievers_results)

retriever nDCG@10
0                    BM25  0.4624
1                 BM25+E5  0.6589
2                BM25+mT5  0.7350
3            SPLADE_pt-BR  0.5982
4  ColBERT-X_mMARCO_pt-BR  0.6483
5                      E5  0.5765
6                 E5 base  0.4138