In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', 500)

In [3]:
ALL_EVALUATIONS="tests/evaluation_06_retrievers_000_009_sampled_50_queries_gpt-4-1106-preview_20231219.tsv"

BM25_RUN="tests/200-queries-passagens-by-BM25-pt_v2_with_query_id_run.txt"
BM25_E5_RUN="tests/bm25_e5_docs_000_999_50_sampled_queries_run.txt"
BM25_MT5_RUN="tests/200-queries-passagens-by-BM25-mT5_v4_with_query_id_run.txt"
SPLADE_RUN="tests/splade_pt_result_with_clueweb_id_run.txt"
COLBERTX_RUN="tests/colbertx_all_znormalized_validation_scores_000_199_run.txt"

In [4]:
E5="tests/e5_docs_000_009_50_sampled_queries.tsv"

In [5]:
retrievers_results = []

### Format GPT-4 evaluations to qrels format

In [6]:
eval_df = pd.read_csv(ALL_EVALUATIONS, sep='\t')

In [7]:
eval_df

query_id                                                  query  \
0            1       Qual a maior característica da fauna brasileira?   
1            1       Qual a maior característica da fauna brasileira?   
2            1       Qual a maior característica da fauna brasileira?   
3            1       Qual a maior característica da fauna brasileira?   
4            1       Qual a maior característica da fauna brasileira?   
...        ...                                                    ...   
1880       199  Quais foram os principais artistas do Impressionismo?   
1881       199  Quais foram os principais artistas do Impressionismo?   
1882       199  Quais foram os principais artistas do Impressionismo?   
1883       199  Quais foram os principais artistas do Impressionismo?   
1884       199  Quais foram os principais artistas do Impressionismo?   

                        passage_id    mT5  splade  colbertx  bm25_e5   bm25  \
0      clueweb22-pt0000-82-13187_0  False   False      True    False  False   
1      clueweb22-pt0000-59-04599_2  False   False      True    False  False   
2     clueweb22-pt0000-64-06285_39   True    True     False    False  False   
3      clueweb22-pt0000-77-06884_1  False    True      True    False  False   
4      clueweb22-pt0000-78-09747_0   True   False     False    False   True   
...                            ...    ...     ...       ...      ...    ...   
1880   clueweb22-pt0001-60-07019_3  False   False     False    False  False   
1881   clueweb22-pt0001-70-17886_8  False   False     False    False  False   
1882   clueweb22-pt0000-50-08513_3  False   False     False    False  False   
1883   clueweb22-pt0001-30-11307_0  False   False     False    False  False   
1884   clueweb22-pt0000-79-06140_4  False   False     False    False  False   

         e5  \
0     False   
1     False   
2     False   
3     False   
4     False   
...     ...   
1880   True   
1881   True   
1882   True   
1883   True   
1884   True   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         passage  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Mamíferos do Brasil - Zoologia | Museu Nacional - UFRJ ➤ Início ➤ Exposições ➤ Zoologia (Acervo) ➤ Insetos ➤ Mamíferos do Brasil Mamíferos do Brasil Uma larga coleção de mamíferos da fauna brasileira. Entre os importantes

In [8]:
eval_df.drop_duplicates("query_id")[['query_id', 'query']]

query_id  \
0            1   
39           2   
82           9   
123         11   
155         13   
189         15   
213         17   
244         20   
295         21   
345         22   
382         24   
427         26   
457         28   
497         47   
546         49   
583         51   
611         54   
650         60   
683         62   
732         64   
766         68   
817         84   
856         95   
906         98   
944        105   
983        113   
1015       115   
1051       117   
1096       126   
1151       127   
1170       128   
1189       136   
1226       147   
1262       152   
1300       153   
1337       154   
1369       160   
1396       161   
1426       163   
1463       167   
1514       170   
1554       172   
1584       180   
1616       181   
1660       182   
1694       189   
1733       193   
1774       195   
1804       196   
1846       199   

                                                                                           query  
0                                               Qual a maior característica da fauna brasileira?  
39                              Por que os países Guiana e Suriname não são filiados a Conmebol?  
82                                            quais países europeus seguem o regime monarquista?  
123      quais os critérios de definição dos monumentos intitulados maravilhas do mundo moderno?  
155                                 Como o Brasil reagiu a epidemia de AIDS no fim do século XX?  
189                                                   Qual a maior torcida de futebol do Brasil?  
213           Quando se realizou o plebiscito popular para definir o sistema político do Brasil?  
244                                            Por que a legislação de um país é tão importante?  
295                                                       Qual o nosso atual sistema de governo?  
345                                                  Qual o sistema de governo da África do Sul?  
382                                                          Por que dividir um país em estados?  
427                                                Como podemos classificar o relevo brasileiro?  
457                                                Existem vantagens ao definir uma moeda única?  
497                                     Como transformar uma cidade pacata em um polo turístico?  
546                                         Quais são os melhores parques nacionais de Portugal?  
583                                                  Qual a melhor cidade para ficar no Jalapão?  
611                                                               Quais são os biomas do Brasil?  
650                            Quando foi criada a consolidação das leis trabalhistas no brasil?  
683                                 Quais partidos já ocuparam o cargo da presidência do Brasil?  
732                            Por que os anos de 80 são considerados a década perdida no Brasil  
766                                    Quais são os principais intérpretes da música brasileira?  
817                                            Qual é a principal cidade do basquete brasileiro?  
856                                         É possível conhecer o Pico da Bandeira com crianças?  
906                                    Qual o critério para classificação para a Copa do Brasil?  
944                                                 Onde está localizada a Praça XV de Novembro?  
983                                                         Fatores de risco para cancer de pele  
1015                                                 Cuidados ao usar materiais perfurocortantes  
1051                                                                   Delirio versus alucinação  
1096                                     Quantas placas são formadas pelos materiais condutores?  
1151                                              O que é a associação em série de um capacitor?  
1170              

#### Check scores distribution on the current qrels

In [9]:
np.unique(eval_df['score'].to_numpy(), return_counts=True)

(array([0, 1, 2, 3]), array([735, 391, 344, 415]))

In [10]:
for group_name, group_df in eval_df.groupby('query_id'):
    print("\nquery_id={}".format(group_name))
    
    print(np.unique(group_df['score'].to_numpy(), return_counts=True))


query_id=1
(array([0, 1, 2, 3]), array([ 5, 20,  9,  5]))

query_id=2
(array([0, 1, 2, 3]), array([38,  2,  1,  2]))

query_id=9
(array([0, 1, 2, 3]), array([24,  4,  9,  4]))

query_id=11
(array([0, 1, 2, 3]), array([15,  8,  7,  2]))

query_id=13
(array([0, 1, 2, 3]), array([13,  8,  9,  4]))

query_id=15
(array([0, 1, 2, 3]), array([ 1, 10,  1, 12]))

query_id=17
(array([0, 1, 2, 3]), array([ 5,  2,  1, 23]))

query_id=20
(array([0, 1, 2, 3]), array([ 4, 26, 17,  4]))

query_id=21
(array([0, 1, 2, 3]), array([22, 13,  1, 14]))

query_id=22
(array([0, 1, 3]), array([25,  7,  5]))

query_id=24
(array([0, 1, 2, 3]), array([17, 17,  9,  2]))

query_id=26
(array([0, 1, 2, 3]), array([ 1,  2,  7, 20]))

query_id=28
(array([0, 1, 2, 3]), array([16,  7, 13,  4]))

query_id=47
(array([0, 1, 2]), array([21, 15, 13]))

query_id=49
(array([0, 1, 2, 3]), array([11, 12, 13,  1]))

query_id=51
(array([0, 1, 2, 3]), array([10, 12,  5,  1]))

query_id=54
(array([1, 2, 3]), array([ 6,  7, 26]))

que

In [11]:
eval_df.groupby('query_id').count()

query  passage_id  mT5  splade  colbertx  bm25_e5  bm25  e5  \
query_id                                                                
1            39          39   39      39        39       39    39  39   
2            43          43   43      43        43       43    43  43   
9            41          41   41      41        41       41    41  41   
11           32          32   32      32        32       32    32  32   
13           34          34   34      34        34       34    34  34   
15           24          24   24      24        24       24    24  24   
17           31          31   31      31        31       31    31  31   
20           51          51   51      51        51       51    51  51   
21           50          50   50      50        50       50    50  50   
22           37          37   37      37        37       37    37  37   
24           45          45   45      45        45       45    45  45   
26           30          30   30      30        30       30    30  30   
28           40          40   40      40        40       40    40  40   
47           49          49   49      49        49       49    49  49   
49           37          37   37      37        37       37    37  37   
51           28          28   28      28        28       28    28  28   
54           39          39   39      39        39       39    39  39   
60           33          33   33      33        33       33    33  33   
62           49          49   49      49        49       49    49  49   
64           34          34   34      34        34       34    34  34   
68           51          51   51      51        51       51    51  51   
84           39          39   39      39        39       39    39  39   
95           50          50   50      50        50       50    50  50   
98           38          38   38      38        38       38    38  38   
105          39          39   39      39        39       39    39  39   
113          32          32   32      32        32       32    32  32   
115          36          36   36      36        36       36    36  36   
117          45          45   45      45        45       45    45  45   
126          55          55   55      55        55       55    55  55   
127          19          19   19      19        19       19    19  19   
128          19          19   19      19        19       19    19  19   
136          37          37   37      37        37       37    37  37   
147          36          36   36      36        36       36    36  36   
152          38          38   38      38        38       38    38  38   
153          37          37   37      37        37       37    37  37   
154          32          32   32      32        32       32    32  32   
160          27          27   27      27        27       27    27  27   
161          30          30   30      30        30       30    30  30   
163          37          37   37      37        37       37    37  37   
167          51          51   51      51        51       51    51  51   
170          40          40   40      40        40       40    40  40   
172          30          30   30      30        30       30    30  30   
180          32          32   32      32        32       32    32  32   
181          44          44   44      44        44       44    44  44   
182          34          34   34      34        34       34    34  34   
189          39          39   39      39        39       39    39  39   
193          41          41   41      41        41       41    41  41   
195          30          30   30      30        30       30    30  30   
196          42          42   42      42        42       42    42  42   
199          39          39   39      39        39       39    39  39   

          passage  score  reasoning  usage  cost  duration  saved_cost  
query_id                                                                
1              39     39         39     39    39        39         

#### Prepare the qrels format for trec_eval tools

In [12]:
eval_df['0'] = '0'

In [13]:
qrels_filename = os.path.join(os.path.dirname(ALL_EVALUATIONS), "{}_qrel.tsv".format(os.path.splitext(os.path.basename(ALL_EVALUATIONS))[0]))

In [14]:
qrels_filename

'tests/evaluation_06_retrievers_000_009_sampled_50_queries_gpt-4-1106-preview_20231219_qrel.tsv'

In [15]:
eval_df.sort_values('query_id')[['query_id', '0', 'passage_id', 'score']].to_csv(qrels_filename, header=None, index=False, sep=" ")

### Compute BM25 NDCG@10

In [16]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    {qrels_filename} tests/200-queries-passagens-by-BM25-pt_v2_with_query_id_run.txt

In [17]:
retrievers_results.append({'retriever':'BM25', 'nDCG@10': result[0].split('\t')[-1]})

In [18]:
retrievers_results

[{'retriever': 'BM25', 'nDCG@10': '0.4656'}]

### Compute BM25 + E5 NDCG@10

In [19]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    {qrels_filename} {BM25_E5_RUN}

In [20]:
retrievers_results.append({'retriever':'BM25+E5', 'nDCG@10': result[0].split('\t')[-1]})

### Compute BM25 + mT5 NDCG@10

In [21]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    {qrels_filename} {BM25_MT5_RUN}

In [22]:
retrievers_results.append({'retriever':'BM25+mT5', 'nDCG@10': result[0].split('\t')[-1]})

### Compute SPLADE NDCG@10

In [23]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    {qrels_filename} {SPLADE_RUN}

In [24]:
retrievers_results.append({'retriever':'SPLADE_pt-BR', 'nDCG@10': result[0].split('\t')[-1]})

### Compute ColBERTX NDCG@10

In [25]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    {qrels_filename} {COLBERTX_RUN}

In [26]:
retrievers_results.append({'retriever':'ColBERT-X_mMARCO_pt-BR', 'nDCG@10': result[0].split('\t')[-1]})

### Prepare E5 retrieval results in run format

In [27]:
e5_df = pd.read_csv(E5, sep="\t")

In [28]:
e5_df.groupby("query_id").head(10).count()

query          500
passage_id     500
score          500
query_id       500
colbertx_id    500
passage        500
dtype: int64

In [29]:
e5_df

query  \
0                                              Qual a maior característica da fauna brasileira?   
1                                              Qual a maior característica da fauna brasileira?   
2                                              Qual a maior característica da fauna brasileira?   
3                                              Qual a maior característica da fauna brasileira?   
4                                              Qual a maior característica da fauna brasileira?   
5                                              Qual a maior característica da fauna brasileira?   
6                                              Qual a maior característica da fauna brasileira?   
7                                              Qual a maior característica da fauna brasileira?   
8                                              Qual a maior característica da fauna brasileira?   
9                                              Qual a maior característica da fauna brasileira?   
10                             Por que os países Guiana e Suriname não são filiados a Conmebol?   
11                             Por que os países Guiana e Suriname não são filiados a Conmebol?   
12                             Por que os países Guiana e Suriname não são filiados a Conmebol?   
13                             Por que os países Guiana e Suriname não são filiados a Conmebol?   
14                             Por que os países Guiana e Suriname não são filiados a Conmebol?   
15                             Por que os países Guiana e Suriname não são filiados a Conmebol?   
16                             Por que os países Guiana e Suriname não são filiados a Conmebol?   
17                             Por que os países Guiana e Suriname não são filiados a Conmebol?   
18                             Por que os países Guiana e Suriname não são filiados a Conmebol?   
19                             Por que os países Guiana e Suriname não são filiados a Conmebol?   
20                                           quais países europeus seguem o regime monarquista?   
21                                           quais países europeus seguem o regime monarquista?   
22                                           quais países europeus seguem o regime monarquista?   
23                                           quais países europeus seguem o regime monarquista?   
24                                           quais países europeus seguem o regime monarquista?   
25                                           quais países europeus seguem o regime monarquista?   
26                                           quais países europeus seguem o regime monarquista?   
27                                           quais países europeus seguem o regime monarquista?   
28                                           quais países europeus seguem o regime monarquista?   
29                                           quais países europeus seguem o regime monarquista?   
30      quais os critérios de definição dos monumentos intitulados maravilhas do mundo moderno?   
31      quais os critérios de definição dos monumentos intitulados maravilhas do mundo moderno?   
32      quais os critérios de definição dos monumentos intitulados maravilhas do mundo moderno?   
33      quais os critérios de definição dos monumentos intitulados maravilhas do mundo moderno?   
34      quais os critérios de definição dos monumentos intitulados maravilhas do mundo moderno?   
35      quais os critérios de definição dos monumentos intitulados maravilhas do mundo moderno?   
36      quais os critérios de definição dos monumentos intitulados maravilhas do mundo moderno?   
37      quais os critérios de definição dos monumentos intitulados maravilhas do mundo moderno?   
38      quais os critérios de definição dos monumentos intitulados maravilhas do mundo moderno?   
39      quais os critérios de definição dos monumentos intitulados maravilhas do mundo moderno?   
40                             

In [30]:
e5_run_df = e5_df.sort_values(["query_id", "score"], ascending=[True, True]).groupby("query_id").head(10)

In [31]:
e5_run_df.shape

(500, 6)

In [33]:
e5_run_df['Q0'] = "Q0"
e5_run_df['comment'] = "gpt-4-1106-preview"
e5_run_df['index'] = np.tile(list(range(1, 11)), 50)

In [34]:
e5_run_df.head(12)

query  \
0                   Qual a maior característica da fauna brasileira?   
1                   Qual a maior característica da fauna brasileira?   
2                   Qual a maior característica da fauna brasileira?   
3                   Qual a maior característica da fauna brasileira?   
4                   Qual a maior característica da fauna brasileira?   
5                   Qual a maior característica da fauna brasileira?   
6                   Qual a maior característica da fauna brasileira?   
7                   Qual a maior característica da fauna brasileira?   
8                   Qual a maior característica da fauna brasileira?   
9                   Qual a maior característica da fauna brasileira?   
10  Por que os países Guiana e Suriname não são filiados a Conmebol?   
11  Por que os países Guiana e Suriname não são filiados a Conmebol?   

                       passage_id     score  query_id  colbertx_id  \
0     clueweb22-pt0000-96-00412_0  0.135295         1      4583617   
1     clueweb22-pt0001-22-15255_0  0.140576         1      5877599   
2     clueweb22-pt0001-90-10791_1  0.144684         1      9091797   
3   clueweb22-pt0002-01-18728_109  0.145850         1      9615207   
4     clueweb22-pt0001-66-11652_2  0.146621         1      7987527   
5    clueweb22-pt0000-34-10889_23  0.150142         1      1658352   
6     clueweb22-pt0000-40-08202_0  0.151151         1      1937987   
7    clueweb22-pt0001-79-01222_35  0.152485         1      8525784   
8     clueweb22-pt0001-26-13111_1  0.153565         1      6065023   
9    clueweb22-pt0000-86-19982_33  0.153591         1      4138910   
10    clueweb22-pt0001-58-12700_6  0.121768         2      7611233   
11    clueweb22-pt0001-73-10674_5  0.124854         2      8315740   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         passage  \
0                                                                      15 ANIMAIS BRASILEIROS: Características e curiosidades Animais brasileiros: nativos, endêmicos e em risco de extinção Fauna quer dizer o conjunto de espécies que vivem em uma determinada região. Por isso, é importante saber diferenciar que quando falamos sobre a fauna brasileira, estamos falando sobre todas as espécies que habitam o Brasil, mas não necessariamente apenas de espécies endêmicas ou nativas, já que alguns animais são considerados espécies invasoras e/ou foram introduzidos pela pessoa humana. Para te mostrar um pouco da nossa incrível fauna, neste post do PeritoAnimal nos focamos em listar aqueles animais brasileiros: nativos e endêmicos que são icônicos na nossa história, além dos animais que só existem no Brasil. Continue lendo e encante-se com a magnitude

In [35]:
e5_run_df[['query_id', 'Q0', "passage_id", "index", "score", "comment"]].to_csv("tests/e5_docs_000_009_50_sampled_queries_run.txt", header=None, index=False, sep=" ")

In [41]:
e5_run_df['score_inv'] = 1 - e5_run_df['score']

In [42]:
e5_run_df[['query_id', 'Q0', "passage_id", "index", "score_inv", "comment"]].to_csv("tests/e5_docs_000_009_50_sampled_queries_score_inv_run.txt", 
                                                                                    header=None, index=False, sep=" ")

#### Compute E5 NDCG@10

In [36]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    {qrels_filename} "tests/e5_docs_000_009_50_sampled_queries_run.txt"

In [37]:
retrievers_results.append({'retriever':'E5', 'nDCG@10': result[0].split('\t')[-1]})

In [43]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    {qrels_filename} "tests/e5_docs_000_009_50_sampled_queries_score_inv_run.txt"

In [44]:
retrievers_results.append({'retriever':'E5_inv', 'nDCG@10': result[0].split('\t')[-1]})

### Check the overall results

In [45]:
pd.DataFrame(retrievers_results)

retriever nDCG@10
0                    BM25  0.4656
1                 BM25+E5  0.6649
2                BM25+mT5  0.7419
3            SPLADE_pt-BR  0.6022
4  ColBERT-X_mMARCO_pt-BR  0.6534
5                      E5  0.5051
6                  E5_inv  0.5819