In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', 500)

In [20]:
ALL_EVALUATIONS="tests/evaluation_05_retrievers_000_009_sampled_50_queries_gpt-4-1106-preview_20231215.tsv"

BM25_RUN="tests/200-queries-passagens-by-BM25-pt_v2_with_query_id_run.txt"
BM25_E5_RUN="tests/bm25_e5_docs_000_999_50_sampled_queries_run.txt"
BM25_MT5_RUN="tests/200-queries-passagens-by-BM25-mT5_v4_with_query_id_run.txt"
SPLADE_RUN="tests/splade_pt_result_with_clueweb_id_run.txt"
COLBERTX_RUN="tests/colbertx_all_znormalized_validation_scores_000_199_run.txt"

In [21]:
retrievers_results = []

### Format GPT-4 evaluations to qrels format

In [22]:
eval_df = pd.read_csv(ALL_EVALUATIONS, sep='\t')

In [23]:
eval_df

query_id                                                  query  \
0            1       Qual a maior característica da fauna brasileira?   
1            1       Qual a maior característica da fauna brasileira?   
2            1       Qual a maior característica da fauna brasileira?   
3            1       Qual a maior característica da fauna brasileira?   
4            1       Qual a maior característica da fauna brasileira?   
...        ...                                                    ...   
1603       199  Quais foram os principais artistas do Impressionismo?   
1604       199  Quais foram os principais artistas do Impressionismo?   
1605       199  Quais foram os principais artistas do Impressionismo?   
1606       199  Quais foram os principais artistas do Impressionismo?   
1607       199  Quais foram os principais artistas do Impressionismo?   

                        passage_id    mT5  splade  colbertx  bm25_e5   bm25  \
0      clueweb22-pt0000-82-13187_0  False   False      True    False  False   
1      clueweb22-pt0000-59-04599_2  False   False      True    False  False   
2     clueweb22-pt0000-64-06285_39   True    True     False    False  False   
3      clueweb22-pt0000-77-06884_1  False    True      True    False  False   
4      clueweb22-pt0000-78-09747_0   True   False     False    False   True   
...                            ...    ...     ...       ...      ...    ...   
1603   clueweb22-pt0000-36-11451_3  False   False     False    False   True   
1604   clueweb22-pt0001-34-12072_2  False   False     False    False   True   
1605   clueweb22-pt0000-71-02344_0  False   False     False    False   True   
1606   clueweb22-pt0001-15-16760_5  False   False     False    False   True   
1607   clueweb22-pt0000-22-00963_2  False   False     False    False   True   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              passage  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Mamíferos do Brasil - Zoologia | Museu Nacional - UFRJ ➤ Início ➤ Exposições ➤ Zoologia (Acervo) ➤ Insetos ➤ Mamíferos do Brasil Mamíferos do Brasil Uma larga coleção de mamíferos da fauna brasileira. Entre os importantes representantes deste acervo de espécimes taxidermizados encontram-se grandes símbolos da diversidade biológica do Brasil. Bugio, Barbado, 

In [24]:
eval_df.drop_duplicates("query_id")[['query_id', 'query']]

query_id  \
0            1   
35           2   
71           9   
108         11   
135         13   
166         15   
189         17   
217         20   
260         21   
301         22   
330         24   
369         26   
397         28   
431         47   
470         49   
504         51   
527         54   
563         60   
595         62   
636         64   
660         68   
703         84   
738         95   
781         98   
814        105   
843        113   
868        115   
901        117   
936        126   
983        127   
1001       128   
1020       136   
1051       147   
1080       152   
1114       153   
1145       154   
1173       160   
1194       161   
1219       163   
1250       167   
1292       170   
1324       172   
1349       180   
1377       181   
1414       182   
1446       189   
1478       193   
1513       195   
1539       196   
1574       199   

                                                                                           query  
0                                               Qual a maior característica da fauna brasileira?  
35                              Por que os países Guiana e Suriname não são filiados a Conmebol?  
71                                            quais países europeus seguem o regime monarquista?  
108      quais os critérios de definição dos monumentos intitulados maravilhas do mundo moderno?  
135                                 Como o Brasil reagiu a epidemia de AIDS no fim do século XX?  
166                                                   Qual a maior torcida de futebol do Brasil?  
189           Quando se realizou o plebiscito popular para definir o sistema político do Brasil?  
217                                            Por que a legislação de um país é tão importante?  
260                                                       Qual o nosso atual sistema de governo?  
301                                                  Qual o sistema de governo da África do Sul?  
330                                                          Por que dividir um país em estados?  
369                                                Como podemos classificar o relevo brasileiro?  
397                                                Existem vantagens ao definir uma moeda única?  
431                                     Como transformar uma cidade pacata em um polo turístico?  
470                                         Quais são os melhores parques nacionais de Portugal?  
504                                                  Qual a melhor cidade para ficar no Jalapão?  
527                                                               Quais são os biomas do Brasil?  
563                            Quando foi criada a consolidação das leis trabalhistas no brasil?  
595                                 Quais partidos já ocuparam o cargo da presidência do Brasil?  
636                            Por que os anos de 80 são considerados a década perdida no Brasil  
660                                    Quais são os principais intérpretes da música brasileira?  
703                                            Qual é a principal cidade do basquete brasileiro?  
738                                         É possível conhecer o Pico da Bandeira com crianças?  
781                                    Qual o critério para classificação para a Copa do Brasil?  
814                                                 Onde está localizada a Praça XV de Novembro?  
843                                                         Fatores de risco para cancer de pele  
868                                                  Cuidados ao usar materiais perfurocortantes  
901                                                                    Delirio versus alucinação  
936                                      Quantas placas são formadas pelos materiais condutores?  
983                                               O que é a associação em série de um capacitor?  
1001              

#### Check scores distribution on the current qrels

In [25]:
np.unique(eval_df['score'].to_numpy(), return_counts=True)

(array([0, 1, 2, 3]), array([600, 327, 293, 388]))

In [26]:
for group_name, group_df in eval_df.groupby('query_id'):
    print("\nquery_id={}".format(group_name))
    
    print(np.unique(group_df['score'].to_numpy(), return_counts=True))


query_id=1
(array([0, 1, 2, 3]), array([ 5, 17,  8,  5]))

query_id=2
(array([0, 1, 2, 3]), array([31,  2,  1,  2]))

query_id=9
(array([0, 1, 2, 3]), array([24,  3,  8,  2]))

query_id=11
(array([0, 1, 2, 3]), array([13,  6,  6,  2]))

query_id=13
(array([0, 1, 2, 3]), array([12,  8,  7,  4]))

query_id=15
(array([0, 1, 2, 3]), array([ 1, 10,  1, 11]))

query_id=17
(array([0, 1, 2, 3]), array([ 4,  1,  1, 22]))

query_id=20
(array([0, 1, 2, 3]), array([ 4, 23, 13,  3]))

query_id=21
(array([0, 1, 2, 3]), array([18,  9,  1, 13]))

query_id=22
(array([0, 1, 3]), array([19,  6,  4]))

query_id=24
(array([0, 1, 2, 3]), array([14, 15,  8,  2]))

query_id=26
(array([0, 1, 2, 3]), array([ 1,  2,  6, 19]))

query_id=28
(array([0, 1, 2, 3]), array([16,  6,  8,  4]))

query_id=47
(array([0, 1, 2]), array([14, 13, 12]))

query_id=49
(array([0, 1, 2, 3]), array([11,  9, 13,  1]))

query_id=51
(array([0, 1, 2, 3]), array([ 8, 10,  4,  1]))

query_id=54
(array([1, 2, 3]), array([ 5,  7, 24]))

que

In [27]:
eval_df.groupby('query_id').count()

query  passage_id  mT5  splade  colbertx  bm25_e5  bm25  passage  \
query_id                                                                     
1            35          35   35      35        35       35    35       35   
2            36          36   36      36        36       36    36       36   
9            37          37   37      37        37       37    37       37   
11           27          27   27      27        27       27    27       27   
13           31          31   31      31        31       31    31       31   
15           23          23   23      23        23       23    23       23   
17           28          28   28      28        28       28    28       28   
20           43          43   43      43        43       43    43       43   
21           41          41   41      41        41       41    41       41   
22           29          29   29      29        29       29    29       29   
24           39          39   39      39        39       39    39       39   
26           28          28   28      28        28       28    28       28   
28           34          34   34      34        34       34    34       34   
47           39          39   39      39        39       39    39       39   
49           34          34   34      34        34       34    34       34   
51           23          23   23      23        23       23    23       23   
54           36          36   36      36        36       36    36       36   
60           32          32   32      32        32       32    32       32   
62           41          41   41      41        41       41    41       41   
64           24          24   24      24        24       24    24       24   
68           43          43   43      43        43       43    43       43   
84           35          35   35      35        35       35    35       35   
95           43          43   43      43        43       43    43       43   
98           33          33   33      33        33       33    33       33   
105          29          29   29      29        29       29    29       29   
113          25          25   25      25        25       25    25       25   
115          33          33   33      33        33       33    33       33   
117          35          35   35      35        35       35    35       35   
126          47          47   47      47        47       47    47       47   
127          18          18   18      18        18       18    18       18   
128          19          19   19      19        19       19    19       19   
136          31          31   31      31        31       31    31       31   
147          29          29   29      29        29       29    29       29   
152          34          34   34      34        34       34    34       34   
153          31          31   31      31        31       31    31       31   
154          28          28   28      28        28       28    28       28   
160          21          21   21      21        21       21    21       21   
161          25          25   25      25        25       25    25       25   
163          31          31   31      31        31       31    31       31   
167          42          42   42      42        42       42    42       42   
170          32          32   32      32        32       32    32       32   
172          25          25   25      25        25       25    25       25   
180          28          28   28      28        28       28    28       28   
181          37          37   37      37        37       37    37       37   
182          32          32   32      32        32       32    32       32   
189          32          32   32      32        32       32    32       32   
193          35          35   35      35        35       35    35       35   
195          26          26   26      26        26       26    26       26   
196          35          35   35      35        35       35    35       35   
199          34          34   34

#### Prepare the qrels format for trec_eval tools

In [28]:
eval_df['0'] = '0'

In [29]:
qrels_filename = os.path.join(os.path.dirname(ALL_EVALUATIONS), "{}_qrel.tsv".format(os.path.splitext(os.path.basename(ALL_EVALUATIONS))[0]))

In [30]:
qrels_filename

'tests/evaluation_05_retrievers_000_009_sampled_50_queries_gpt-4-1106-preview_20231215_qrel.tsv'

In [31]:
eval_df.sort_values('query_id')[['query_id', '0', 'passage_id', 'score']].to_csv(qrels_filename, header=None, index=False, sep=" ")

### Compute BM25 NDCG@10

In [32]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    {qrels_filename} tests/200-queries-passagens-by-BM25-pt_v2_with_query_id_run.txt

In [33]:
retrievers_results.append({'retriever':'BM25', 'nDCG@10': result[0].split('\t')[-1]})

In [34]:
retrievers_results

[{'retriever': 'BM25', 'nDCG@10': '0.4705'}]

### Compute BM25 + E5 NDCG@10

In [35]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    {qrels_filename} {BM25_E5_RUN}

In [36]:
retrievers_results.append({'retriever':'BM25+E5', 'nDCG@10': result[0].split('\t')[-1]})

### Compute BM25 + mT5 NDCG@10

In [37]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    {qrels_filename} {BM25_MT5_RUN}

In [38]:
retrievers_results.append({'retriever':'BM25+mT5', 'nDCG@10': result[0].split('\t')[-1]})

### Compute SPLADE NDCG@10

In [39]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    {qrels_filename} {SPLADE_RUN}

In [40]:
retrievers_results.append({'retriever':'SPLADE_pt-BR', 'nDCG@10': result[0].split('\t')[-1]})

### Compute ColBERTX NDCG@10

In [41]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    {qrels_filename} {COLBERTX_RUN}

In [42]:
retrievers_results.append({'retriever':'ColBERT-X_mMARCO_pt-BR', 'nDCG@10': result[0].split('\t')[-1]})

### Check the overall results

In [43]:
pd.DataFrame(retrievers_results)

retriever nDCG@10
0                    BM25  0.4705
1                 BM25+E5  0.6738
2                BM25+mT5  0.7525
3            SPLADE_pt-BR  0.6062
4  ColBERT-X_mMARCO_pt-BR  0.6596