In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', 500)

In [3]:
ALL_EVALUATIONS="tests/evaluation_08_retrievers_000_009_sampled_50_queries_gpt-4-1106-preview_20231227.tsv"

BM25_RUN="tests/200-queries-passagens-by-BM25-pt_v2_with_query_id_run.txt"
BM25_E5_RUN="tests/bm25_e5_docs_000_999_50_sampled_queries_run.txt"
BM25_MT5_RUN="tests/200-queries-passagens-by-BM25-mT5_v4_with_query_id_run.txt"
SPLADE_RUN="tests/splade_pt_result_with_clueweb_id_run.txt"
COLBERTX_RUN="tests/colbertx_all_znormalized_validation_scores_000_199_run.txt"
E5_RUN="tests/e5_docs_000_009_50_sampled_queries_score_inv_run.txt"
E5_BASE_RUN="tests/e5_base_docs_000_009_50_sampled_queries_score_inv_run.txt"

In [4]:
BM25_1M="tests/bm25_1M_docs_000_009_sampled_50_queries.tsv"

In [5]:
retrievers_results = []

### Format GPT-4 evaluations to qrels format

In [6]:
eval_df = pd.read_csv(ALL_EVALUATIONS, sep='\t')

In [7]:
eval_df

query_id                                                  query  \
0            1       Qual a maior característica da fauna brasileira?   
1            1       Qual a maior característica da fauna brasileira?   
2            1       Qual a maior característica da fauna brasileira?   
3            1       Qual a maior característica da fauna brasileira?   
4            1       Qual a maior característica da fauna brasileira?   
...        ...                                                    ...   
2584       199  Quais foram os principais artistas do Impressionismo?   
2585       199  Quais foram os principais artistas do Impressionismo?   
2586       199  Quais foram os principais artistas do Impressionismo?   
2587       199  Quais foram os principais artistas do Impressionismo?   
2588       199  Quais foram os principais artistas do Impressionismo?   

                        passage_id    mT5  splade  colbertx  bm25_e5   bm25  \
0      clueweb22-pt0000-82-13187_0  False   False      True    False  False   
1      clueweb22-pt0000-59-04599_2  False   False      True    False  False   
2     clueweb22-pt0000-64-06285_39   True    True     False    False  False   
3      clueweb22-pt0000-77-06884_1  False    True      True    False  False   
4      clueweb22-pt0000-78-09747_0   True   False     False    False   True   
...                            ...    ...     ...       ...      ...    ...   
2584   clueweb22-pt0000-24-02686_5  False   False     False    False  False   
2585   clueweb22-pt0000-69-09620_5  False   False     False    False  False   
2586   clueweb22-pt0001-31-14853_1  False   False     False    False  False   
2587   clueweb22-pt0000-51-14268_2  False   False     False    False  False   
2588   clueweb22-pt0000-87-13460_0  False   False     False    False  False   

         e5  e5_base  bm25_1M  \
0     False    False    False   
1     False    False    False   
2     False     True    False   
3     False    False    False   
4     False    False    False   
...     ...      ...      ...   
2584  False    False     True   
2585  False    False     True   
2586  False    False     True   
2587  False    False     True   
2588  False    False     True   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          passage  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 

In [8]:
eval_df.drop_duplicates("query_id")[['query_id', 'query']]

query_id  \
0            1   
54           2   
116          9   
170         11   
218         13   
263         15   
297         17   
339         20   
406         21   
468         22   
515         24   
579         26   
628         28   
687         47   
753         49   
804         51   
844         54   
893         60   
937         62   
1000        64   
1044        68   
1109        84   
1158        95   
1222        98   
1276       105   
1333       113   
1375       115   
1425       117   
1490       126   
1560       127   
1589       128   
1627       136   
1680       147   
1731       152   
1784       153   
1840       154   
1882       160   
1925       161   
1964       163   
2012       167   
2079       170   
2135       172   
2178       180   
2224       181   
2286       182   
2332       189   
2386       193   
2438       195   
2480       196   
2540       199   

                                                                                           query  
0                                               Qual a maior característica da fauna brasileira?  
54                              Por que os países Guiana e Suriname não são filiados a Conmebol?  
116                                           quais países europeus seguem o regime monarquista?  
170      quais os critérios de definição dos monumentos intitulados maravilhas do mundo moderno?  
218                                 Como o Brasil reagiu a epidemia de AIDS no fim do século XX?  
263                                                   Qual a maior torcida de futebol do Brasil?  
297           Quando se realizou o plebiscito popular para definir o sistema político do Brasil?  
339                                            Por que a legislação de um país é tão importante?  
406                                                       Qual o nosso atual sistema de governo?  
468                                                  Qual o sistema de governo da África do Sul?  
515                                                          Por que dividir um país em estados?  
579                                                Como podemos classificar o relevo brasileiro?  
628                                                Existem vantagens ao definir uma moeda única?  
687                                     Como transformar uma cidade pacata em um polo turístico?  
753                                         Quais são os melhores parques nacionais de Portugal?  
804                                                  Qual a melhor cidade para ficar no Jalapão?  
844                                                               Quais são os biomas do Brasil?  
893                            Quando foi criada a consolidação das leis trabalhistas no brasil?  
937                                 Quais partidos já ocuparam o cargo da presidência do Brasil?  
1000                           Por que os anos de 80 são considerados a década perdida no Brasil  
1044                                   Quais são os principais intérpretes da música brasileira?  
1109                                           Qual é a principal cidade do basquete brasileiro?  
1158                                        É possível conhecer o Pico da Bandeira com crianças?  
1222                                   Qual o critério para classificação para a Copa do Brasil?  
1276                                                Onde está localizada a Praça XV de Novembro?  
1333                                                        Fatores de risco para cancer de pele  
1375                                                 Cuidados ao usar materiais perfurocortantes  
1425                                                                   Delirio versus alucinação  
1490                                     Quantas placas são formadas pelos materiais condutores?  
1560                                              O que é a associação em série de um capacitor?  
1589              

#### Check scores distribution on the current qrels

In [9]:
np.unique(eval_df['score'].to_numpy(), return_counts=True)

(array([0, 1, 2, 3]), array([1196,  517,  407,  469]))

In [10]:
for group_name, group_df in eval_df.groupby('query_id'):
    print("\nquery_id={}".format(group_name))
    
    print(np.unique(group_df['score'].to_numpy(), return_counts=True))


query_id=1
(array([0, 1, 2, 3]), array([ 6, 30, 11,  7]))

query_id=2
(array([0, 1, 2, 3]), array([57,  2,  1,  2]))

query_id=9
(array([0, 1, 2, 3]), array([36,  4,  9,  5]))

query_id=11
(array([0, 1, 2, 3]), array([29, 10,  7,  2]))

query_id=13
(array([0, 1, 2, 3]), array([21,  9, 11,  4]))

query_id=15
(array([0, 1, 2, 3]), array([ 9, 12,  1, 12]))

query_id=17
(array([0, 1, 2, 3]), array([11,  4,  1, 26]))

query_id=20
(array([0, 1, 2, 3]), array([10, 35, 18,  4]))

query_id=21
(array([0, 1, 2, 3]), array([32, 15,  1, 14]))

query_id=22
(array([0, 1, 3]), array([34,  8,  5]))

query_id=24
(array([0, 1, 2, 3]), array([36, 17,  9,  2]))

query_id=26
(array([0, 1, 2, 3]), array([13,  5,  8, 23]))

query_id=28
(array([0, 1, 2, 3]), array([33,  9, 13,  4]))

query_id=47
(array([0, 1, 2]), array([29, 21, 16]))

query_id=49
(array([0, 1, 2, 3]), array([18, 17, 15,  1]))

query_id=51
(array([0, 1, 2, 3]), array([17, 14,  8,  1]))

query_id=54
(array([0, 1, 2, 3]), array([ 1, 11,  8, 29]

In [11]:
eval_df.groupby('query_id').count()

query  passage_id  mT5  splade  colbertx  bm25_e5  bm25  e5  \
query_id                                                                
1            54          54   54      54        54       54    54  54   
2            62          62   62      62        62       62    62  62   
9            54          54   54      54        54       54    54  54   
11           48          48   48      48        48       48    48  48   
13           45          45   45      45        45       45    45  45   
15           34          34   34      34        34       34    34  34   
17           42          42   42      42        42       42    42  42   
20           67          67   67      67        67       67    67  67   
21           62          62   62      62        62       62    62  62   
22           47          47   47      47        47       47    47  47   
24           64          64   64      64        64       64    64  64   
26           49          49   49      49        49       49    49  49   
28           59          59   59      59        59       59    59  59   
47           66          66   66      66        66       66    66  66   
49           51          51   51      51        51       51    51  51   
51           40          40   40      40        40       40    40  40   
54           49          49   49      49        49       49    49  49   
60           44          44   44      44        44       44    44  44   
62           63          63   63      63        63       63    63  63   
64           44          44   44      44        44       44    44  44   
68           65          65   65      65        65       65    65  65   
84           49          49   49      49        49       49    49  49   
95           64          64   64      64        64       64    64  64   
98           54          54   54      54        54       54    54  54   
105          57          57   57      57        57       57    57  57   
113          42          42   42      42        42       42    42  42   
115          50          50   50      50        50       50    50  50   
117          65          65   65      65        65       65    65  65   
126          70          70   70      70        70       70    70  70   
127          29          29   29      29        29       29    29  29   
128          38          38   38      38        38       38    38  38   
136          53          53   53      53        53       53    53  53   
147          51          51   51      51        51       51    51  51   
152          53          53   53      53        53       53    53  53   
153          56          56   56      56        56       56    56  56   
154          42          42   42      42        42       42    42  42   
160          43          43   43      43        43       43    43  43   
161          39          39   39      39        39       39    39  39   
163          48          48   48      48        48       48    48  48   
167          67          67   67      67        67       67    67  67   
170          56          56   56      56        56       56    56  56   
172          43          43   43      43        43       43    43  43   
180          46          46   46      46        46       46    46  46   
181          62          62   62      62        62       62    62  62   
182          46          46   46      46        46       46    46  46   
189          54          54   54      54        54       54    54  54   
193          52          52   52      52        52       52    52  52   
195          42          42   42      42        42       42    42  42   
196          60          60   60      60        60       60    60  60   
199          49          49   49      49        49       49    49  49   

          e5_base  bm25_1M  passage  score  reasoning  usage  cost  duration  \
query_id                                                                       
1              54       54       54     54         54

#### Prepare the qrels format for trec_eval tools

In [12]:
eval_df['0'] = '0'

In [13]:
qrels_filename = os.path.join(os.path.dirname(ALL_EVALUATIONS), "{}_qrel.txt".format(os.path.splitext(os.path.basename(ALL_EVALUATIONS))[0]))

In [14]:
qrels_filename

'tests/evaluation_08_retrievers_000_009_sampled_50_queries_gpt-4-1106-preview_20231227_qrel.txt'

In [15]:
eval_df.sort_values('query_id')[['query_id', '0', 'passage_id', 'score']].to_csv(qrels_filename, header=None, index=False, sep=" ")

### Compute BM25 nDCG@10

In [16]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    {qrels_filename} tests/200-queries-passagens-by-BM25-pt_v2_with_query_id_run.txt

In [17]:
retrievers_results.append({'retriever':'BM25', 'nDCG@10': result[0].split('\t')[-1]})

In [18]:
retrievers_results

[{'retriever': 'BM25', 'nDCG@10': '0.4594'}]

### Compute BM25 + E5 nDCG@10

In [19]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    {qrels_filename} {BM25_E5_RUN}

In [20]:
retrievers_results.append({'retriever':'BM25+E5', 'nDCG@10': result[0].split('\t')[-1]})

### Compute BM25 + mT5 nDCG@10

In [21]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    {qrels_filename} {BM25_MT5_RUN}

In [22]:
retrievers_results.append({'retriever':'BM25+mT5', 'nDCG@10': result[0].split('\t')[-1]})

### Compute SPLADE nDCG@10

In [23]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    {qrels_filename} {SPLADE_RUN}

In [24]:
retrievers_results.append({'retriever':'SPLADE_pt-BR', 'nDCG@10': result[0].split('\t')[-1]})

### Compute ColBERTX nDCG@10

In [25]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    {qrels_filename} {COLBERTX_RUN}

In [26]:
retrievers_results.append({'retriever':'ColBERT-X_mMARCO_pt-BR', 'nDCG@10': result[0].split('\t')[-1]})

### Compute E5 nDCG@10

In [27]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    {qrels_filename} {E5_RUN}

In [28]:
retrievers_results.append({'retriever':'E5', 'nDCG@10': result[0].split('\t')[-1]})

### Compute E5 base nDCG@10

In [29]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    {qrels_filename} {E5_BASE_RUN}

In [30]:
retrievers_results.append({'retriever':'E5 base', 'nDCG@10': result[0].split('\t')[-1]})

### Prepare BM25 1M retrieval results in run format

In [31]:
bm25_1M_df = pd.read_csv(BM25_1M, sep="\t")

In [32]:
bm25_1M_df.groupby("query_id").head(10).count()

query_id       500
Q0             500
colbertx_id    500
position       500
score          500
comment        500
passage_id     500
query          500
passage        500
dtype: int64

In [33]:
bm25_1M_df

query_id  Q0  colbertx_id  position      score   comment  \
0           1  Q0      3783987         1   9.434800  Anserini   
1           1  Q0      2630333         2   9.375400  Anserini   
2           1  Q0      7499132         3   9.197300  Anserini   
3           1  Q0      8210163         4   9.089900  Anserini   
4           1  Q0      1534772         5   9.027000  Anserini   
5           1  Q0      1350626         6   8.997400  Anserini   
6           1  Q0      5313492         7   8.834200  Anserini   
7           1  Q0      7018738         8   8.606900  Anserini   
8           1  Q0      9847927         9   8.490100  Anserini   
9           1  Q0      1718806        10   8.463300  Anserini   
10          2  Q0      2810821         1  14.607200  Anserini   
11          2  Q0      5176125         2  14.581500  Anserini   
12          2  Q0      2724040         3  14.387600  Anserini   
13          2  Q0      6534521         4  14.123500  Anserini   
14          2  Q0      2207685         5  14.002100  Anserini   
15          2  Q0      2615478         6  13.925600  Anserini   
16          2  Q0      2603733         7  13.856300  Anserini   
17          2  Q0      8968120         8  13.776700  Anserini   
18          2  Q0      1325979         9  13.643300  Anserini   
19          2  Q0      1544120        10  13.643299  Anserini   
20          9  Q0      1419835         1  10.777200  Anserini   
21          9  Q0      9076279         2  10.393300  Anserini   
22          9  Q0      1004749         3  10.270000  Anserini   
23          9  Q0      6523569         4   9.969400  Anserini   
24          9  Q0      7028130         5   9.722700  Anserini   
25          9  Q0      4770801         6   9.713700  Anserini   
26          9  Q0      5757530         7   9.667300  Anserini   
27          9  Q0      7547756         8   9.666700  Anserini   
28          9  Q0      4171475         9   9.585600  Anserini   
29          9  Q0      7286760        10   9.550900  Anserini   
30         11  Q0      3454916         1  11.787600  Anserini   
31         11  Q0      8494780         2  11.701100  Anserini   
32         11  Q0      8788743         3  11.691700  Anserini   
33         11  Q0      3011709         4  11.661800  Anserini   
34         11  Q0      9882392         5  11.632900  Anserini   
35         11  Q0      5936642         6  11.572400  Anserini   
36         11  Q0      2355066         7  11.448700  Anserini   
37         11  Q0      4686277         8  11.242500  Anserini   
38         11  Q0      9134103         9  11.136800  Anserini   
39         11  Q0      4333136        10  11.024100  Anserini   
40         13  Q0      4811480         1  19.796700  Anserini   
41         13  Q0      8218787         2  12.964200  Anserini   
42         13  Q0      2990034         3  12.958000  Anserini   
43         13  Q0      4288849         4  12.809800  Anserini   
44         13  Q0      5389749         5  12.681300  Anserini   
45         13  Q0      5966879         6  12.666600  Anserini   
46         13  Q0      9235155         7  12.346900  Anserini   
47         13  Q0      1793029         8  12.060400  Anserini   
48         13  Q0      6656252         9  12.011800  Anserini   
49         13  Q0      1326250        10  11.616500  Anserini   
50         15  Q0      6251483         1  12.286300  Anserini   
51         15  Q0      9259692         2  12.045700  Anserini   
52         15  Q0      8082555         3  11.930800  Anserini   
53         15  Q0      4377704         4  11.566000  Anserini   
54         15  Q0      4168317         5  11.524700  Anserini   
55         15  Q0      6251482         6  11.295100  Anserini   
56         15  Q0      6246727         7  11.159500  Anserini   
57         15  Q0      7601510         8  10.831600  Anserini   
58         15  Q0      4627315         9  10.780600  Anserini   
59         15  Q0      4872268        10  10.757800  Anserini   
60         17  Q0      1242320         1

In [34]:
bm25_1M_run_df = bm25_1M_df.sort_values(["query_id", "score"], ascending=[True, False]).groupby("query_id").head(10)

In [35]:
bm25_1M_run_df.shape

(500, 9)

In [36]:
bm25_1M_run_df['Q0'] = "Q0"
bm25_1M_run_df['comment'] = "gpt-4-1106-preview"
bm25_1M_run_df['index'] = np.tile(list(range(1, 11)), 50)

In [37]:
bm25_1M_run_df.head(12)

query_id  Q0  colbertx_id  position    score             comment  \
0          1  Q0      3783987         1   9.4348  gpt-4-1106-preview   
1          1  Q0      2630333         2   9.3754  gpt-4-1106-preview   
2          1  Q0      7499132         3   9.1973  gpt-4-1106-preview   
3          1  Q0      8210163         4   9.0899  gpt-4-1106-preview   
4          1  Q0      1534772         5   9.0270  gpt-4-1106-preview   
5          1  Q0      1350626         6   8.9974  gpt-4-1106-preview   
6          1  Q0      5313492         7   8.8342  gpt-4-1106-preview   
7          1  Q0      7018738         8   8.6069  gpt-4-1106-preview   
8          1  Q0      9847927         9   8.4901  gpt-4-1106-preview   
9          1  Q0      1718806        10   8.4633  gpt-4-1106-preview   
10         2  Q0      2810821         1  14.6072  gpt-4-1106-preview   
11         2  Q0      5176125         2  14.5815  gpt-4-1106-preview   

                       passage_id  \
0   clueweb22-pt0000-79-16312_218   
1     clueweb22-pt0000-55-12305_1   
2     clueweb22-pt0001-56-07770_0   
3    clueweb22-pt0001-71-09093_76   
4    clueweb22-pt0000-32-06211_20   
5     clueweb22-pt0000-28-03516_7   
6     clueweb22-pt0001-10-17851_5   
7     clueweb22-pt0001-46-01174_0   
8     clueweb22-pt0002-07-02323_1   
9     clueweb22-pt0000-35-18523_0   
10    clueweb22-pt0000-59-10618_0   
11    clueweb22-pt0001-08-01097_0   

                                                               query  \
0                   Qual a maior característica da fauna brasileira?   
1                   Qual a maior característica da fauna brasileira?   
2                   Qual a maior característica da fauna brasileira?   
3                   Qual a maior característica da fauna brasileira?   
4                   Qual a maior característica da fauna brasileira?   
5                   Qual a maior característica da fauna brasileira?   
6                   Qual a maior característica da fauna brasileira?   
7                   Qual a maior característica da fauna brasileira?   
8                   Qual a maior característica da fauna brasileira?   
9                   Qual a maior característica da fauna brasileira?   
10  Por que os países Guiana e Suriname não são filiados a Conmebol?   
11  Por que os países Guiana e Suriname não são filiados a Conmebol?   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           passage  \
0                                                                                                                                                          Fonte: http://www.gazetadopovo.com.br/esportes/olimpiadas/conteudo.phtml?tit=Cameron-aposta-na-Olimpiada-para-recuperar-economia&id=1279366 Tec

In [39]:
bm25_1M_run_df[['query_id', 'Q0', "passage_id", "index", "score", "comment"]].to_csv("tests/bm25_1M_docs_000_009_50_sampled_queries_run.txt", 
                                                                                     header=None, index=False, sep=" ")

#### Compute BM25 1M NDCG@10

In [40]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    {qrels_filename} "tests/bm25_1M_docs_000_009_50_sampled_queries_run.txt"

In [41]:
retrievers_results.append({'retriever':'BM25 1M', 'nDCG@10': result[0].split('\t')[-1]})

### Check the overall results

In [42]:
pd.DataFrame(retrievers_results)

retriever nDCG@10
0                    BM25  0.4594
1                 BM25+E5  0.6558
2                BM25+mT5  0.7341
3            SPLADE_pt-BR  0.5963
4  ColBERT-X_mMARCO_pt-BR  0.6473
5                      E5  0.5744
6                 E5 base  0.4120
7                 BM25 1M  0.3263