In [1]:
import pandas as pd
import numpy as np
import os

In [17]:
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', 500)

In [158]:
ALL_EVALUATIONS="tests/evaluation_04_retrievers_000_009_sampled_50_queries_gpt-4-1106-preview_20231211.tsv"
BM25="../trabalho_final/validation_queries_retrievals/200-queries-passagens-by-BM25-pt_v2.tsv"
BM25_E5="tests/bm25_e5_docs_000_999_50_sampled_queries.tsv"
BM25_MT5="../trabalho_final/validation_queries_retrievals/200-queries-passagens-by-BM25-mT5_v4_with_query_id.tsv"
SPLADE="../trabalho_final/validation_queries_retrievals/splade_pt_result_with_clueweb_id.tsv"
COLBERTX="../trabalho_final/validation_queries_retrievals/colbertx_all_znormalized_validation_scores_000_199.tsv"

In [218]:
retrievers_results = []

### Format GPT-4 evaluations to qrels format

In [3]:
eval_df = pd.read_csv(ALL_EVALUATIONS, sep='\t')

In [4]:
eval_df

query_id                                              query  \
0            1   Qual a maior característica da fauna brasileira?   
1            1   Qual a maior característica da fauna brasileira?   
2            1   Qual a maior característica da fauna brasileira?   
3            1   Qual a maior característica da fauna brasileira?   
4            1   Qual a maior característica da fauna brasileira?   
...        ...                                                ...   
1284       199  Quais foram os principais artistas do Impressi...   
1285       199  Quais foram os principais artistas do Impressi...   
1286       199  Quais foram os principais artistas do Impressi...   
1287       199  Quais foram os principais artistas do Impressi...   
1288       199  Quais foram os principais artistas do Impressi...   

                        passage_id    mT5  splade  colbertx  bm25_e5  \
0      clueweb22-pt0000-82-13187_0  False   False      True    False   
1      clueweb22-pt0000-59-04599_2  False   False      True    False   
2     clueweb22-pt0000-64-06285_39   True    True     False    False   
3      clueweb22-pt0000-77-06884_1  False    True      True    False   
4      clueweb22-pt0000-78-09747_0   True   False     False    False   
...                            ...    ...     ...       ...      ...   
1284   clueweb22-pt0001-84-17796_0   True    True      True     True   
1285   clueweb22-pt0001-84-17796_1  False   False      True    False   
1286   clueweb22-pt0001-70-17886_9  False   False     False     True   
1287   clueweb22-pt0000-79-11166_1  False   False     False     True   
1288   clueweb22-pt0001-94-07405_4  False   False     False     True   

                                                passage  score  \
0     Mamíferos do Brasil - Zoologia | Museu Naciona...      1   
1     Segundo uma lista levantada pelo Comitê Brasil...      1   
2     A exuberante fauna e flora brasileiras, relata...      3   
3     O tamanho do Brasil e a grande variedade de cl...      1   
4     Onça-pintada - Escola Kids Qual matéria está p...      1   
...                                                 ...    ...   
1284  Artistas Impressionistas: lista dos principais...      3   
1285  - Francesco Filippini (pintor italiano) - Gius...      2   
1286  São duas as fontes mais importantes do impress...      3   
1287  O impressionismo foi um movimento de arte que ...      3   
1288  A vertente romântica se configurou pela exibiç...      3   

                                              reasoning  \
0     A passagem lista vários mamíferos da fauna bra...   
1     A passagem descreve várias espécies de aves en...   
2     A passagem menciona que o Brasil tem a maior b...   
3     A passagem menciona a alta biodiversidade do B...   
4     A passagem menciona que a onça-pintada é um do...   
...                                                 ...   
1284  A passagem fornece uma lista detalhada dos pri...   
1285  A passagem lista vários artistas, incluindo al...   
1286  A passagem responde diretamente à pergunta, li...   
1287  A passagem responde diretamente à pergunta, li...   
1288  A passagem responde diretamente à pergunta, li...   

                                                  usage     cost  duration  \
0     {'prompt_tokens': 765, 'completion_tokens': 75...  0.00000  6.693229   
1     {'prompt_tokens': 860, 'completion_tokens': 82...  0.00000  5.163547   
2     {'prompt_tokens': 840, 'completion_tokens': 46...  0.00000  5.185688   
3     {'prompt_tokens': 812, 'completion_tokens': 81...  0.00000  5.882017   
4     {'prompt_tokens': 805, 'completion_tokens': 96...  0.00000  5.774773   
...                                                 ...      ...       ...   
1284  {'prompt_tokens': 888, 'completion_tokens': 41...  0.00000  2.660084   
1285  {'prompt_tokens': 820, 'completion_tokens': 87...  0.00000  7.354066   
1286  {'prompt_tokens': 808, 'completion_tokens': 48...  0.02712  4.073626   
1287  {'prompt_tokens': 741, '

In [132]:
eval_df.drop_duplicates("query_id")[['query_id', 'query']]

query_id  \
0            1   
29           2   
57           9   
85          11   
109         13   
134         15   
151         17   
171         20   
204         21   
237         22   
260         24   
290         26   
314         28   
341         47   
371         49   
399         51   
419         54   
448         60   
476         62   
508         64   
528         68   
561         84   
589         95   
626         98   
652        105   
678        113   
698        115   
724        117   
752        126   
791        127   
807        128   
824        136   
847        147   
872        152   
899        153   
922        154   
941        160   
961        161   
982        163   
1008       167   
1043       170   
1070       172   
1090       180   
1111       181   
1140       182   
1164       189   
1192       193   
1218       195   
1236       196   
1264       199   

                                                                                           query  
0                                               Qual a maior característica da fauna brasileira?  
29                              Por que os países Guiana e Suriname não são filiados a Conmebol?  
57                                            quais países europeus seguem o regime monarquista?  
85       quais os critérios de definição dos monumentos intitulados maravilhas do mundo moderno?  
109                                 Como o Brasil reagiu a epidemia de AIDS no fim do século XX?  
134                                                   Qual a maior torcida de futebol do Brasil?  
151           Quando se realizou o plebiscito popular para definir o sistema político do Brasil?  
171                                            Por que a legislação de um país é tão importante?  
204                                                       Qual o nosso atual sistema de governo?  
237                                                  Qual o sistema de governo da África do Sul?  
260                                                          Por que dividir um país em estados?  
290                                                Como podemos classificar o relevo brasileiro?  
314                                                Existem vantagens ao definir uma moeda única?  
341                                     Como transformar uma cidade pacata em um polo turístico?  
371                                         Quais são os melhores parques nacionais de Portugal?  
399                                                  Qual a melhor cidade para ficar no Jalapão?  
419                                                               Quais são os biomas do Brasil?  
448                            Quando foi criada a consolidação das leis trabalhistas no brasil?  
476                                 Quais partidos já ocuparam o cargo da presidência do Brasil?  
508                            Por que os anos de 80 são considerados a década perdida no Brasil  
528                                    Quais são os principais intérpretes da música brasileira?  
561                                            Qual é a principal cidade do basquete brasileiro?  
589                                         É possível conhecer o Pico da Bandeira com crianças?  
626                                    Qual o critério para classificação para a Copa do Brasil?  
652                                                 Onde está localizada a Praça XV de Novembro?  
678                                                         Fatores de risco para cancer de pele  
698                                                  Cuidados ao usar materiais perfurocortantes  
724                                                                    Delirio versus alucinação  
752                                      Quantas placas são formadas pelos materiais condutores?  
791                                               O que é a associação em série de um capacitor?  
807               

#### Check scores distribution on the current qrels

In [103]:
np.unique(eval_df['score'].to_numpy(), return_counts=True)

(array([0, 1, 2, 3]), array([435, 247, 252, 355]))

In [104]:
for group_name, group_df in eval_df.groupby('query_id'):
    print("\nquery_id={}".format(group_name))
    
    print(np.unique(group_df['score'].to_numpy(), return_counts=True))


query_id=1
(array([0, 1, 2, 3]), array([ 5, 11,  8,  5]))

query_id=2
(array([0, 1, 2, 3]), array([23,  2,  1,  2]))

query_id=9
(array([0, 1, 2, 3]), array([15,  3,  8,  2]))

query_id=11
(array([0, 1, 2, 3]), array([10,  6,  6,  2]))

query_id=13
(array([0, 1, 2, 3]), array([6, 8, 7, 4]))

query_id=15
(array([1, 3]), array([ 7, 10]))

query_id=17
(array([0, 2, 3]), array([ 2,  1, 17]))

query_id=20
(array([0, 1, 2, 3]), array([ 3, 14, 13,  3]))

query_id=21
(array([0, 1, 2, 3]), array([12,  8,  1, 12]))

query_id=22
(array([0, 1, 3]), array([15,  4,  4]))

query_id=24
(array([0, 1, 2, 3]), array([ 6, 14,  8,  2]))

query_id=26
(array([1, 2, 3]), array([ 1,  5, 18]))

query_id=28
(array([0, 1, 2, 3]), array([11,  5,  7,  4]))

query_id=47
(array([0, 1, 2]), array([10, 11,  9]))

query_id=49
(array([0, 1, 2, 3]), array([10,  7, 10,  1]))

query_id=51
(array([0, 1, 2, 3]), array([ 6, 10,  3,  1]))

query_id=54
(array([1, 2, 3]), array([ 3,  4, 22]))

query_id=60
(array([0, 1, 3]), arra

In [92]:
eval_df.groupby('query_id').count()

query  passage_id  mT5  splade  colbertx  bm25_e5  passage  score  \
query_id                                                                      
1            29          29   29      29        29       29       29     29   
2            28          28   28      28        28       28       28     28   
9            28          28   28      28        28       28       28     28   
11           24          24   24      24        24       24       24     24   
13           25          25   25      25        25       25       25     25   
15           17          17   17      17        17       17       17     17   
17           20          20   20      20        20       20       20     20   
20           33          33   33      33        33       33       33     33   
21           33          33   33      33        33       33       33     33   
22           23          23   23      23        23       23       23     23   
24           30          30   30      30        30       30       30     30   
26           24          24   24      24        24       24       24     24   
28           27          27   27      27        27       27       27     27   
47           30          30   30      30        30       30       30     30   
49           28          28   28      28        28       28       28     28   
51           20          20   20      20        20       20       20     20   
54           29          29   29      29        29       29       29     29   
60           28          28   28      28        28       28       28     28   
62           32          32   32      32        32       32       32     32   
64           20          20   20      20        20       20       20     20   
68           33          33   33      33        33       33       33     33   
84           28          28   28      28        28       28       28     28   
95           37          37   37      37        37       37       37     37   
98           26          26   26      26        26       26       26     26   
105          26          26   26      26        26       26       26     26   
113          20          20   20      20        20       20       20     20   
115          26          26   26      26        26       26       26     26   
117          28          28   28      28        28       28       28     28   
126          39          39   39      39        39       39       39     39   
127          16          16   16      16        16       16       16     16   
128          17          17   17      17        17       17       17     17   
136          23          23   23      23        23       23       23     23   
147          25          25   25      25        25       25       25     25   
152          27          27   27      27        27       27       27     27   
153          23          23   23      23        23       23       23     23   
154          19          19   19      19        19       19       19     19   
160          20          20   20      20        20       20       20     20   
161          21          21   21      21        21       21       21     21   
163          26          26   26      26        26       26       26     26   
167          35          35   35      35        35       35       35     35   
170          27          27   27      27        27       27       27     27   
172          20          20   20      20        20       20       20     20   
180          21          21   21      21        21       21       21     21   
181          29          29   29      29        29       29       29     29   
182          24          24   24      24        24       24       24     24   
189          28          28   28      28        28       28       28     28   
193          26          26   26      26        26       26       26     26   
195          18          18   18      18        18       18       18     18   
196          28          28   28      28        28       28 

#### Prepare the qrels format for trec_eval tools

In [100]:
eval_df['0'] = '0'

In [93]:
passages_order = list(range(0, eval_df.shape[0]))

In [95]:
np.random.shuffle(passages_order)

In [101]:
eval_df.iloc[passages_order].sort_values('query_id')[['query_id', '0', 'passage_id', 'score']].to_csv("tests/evaluation_04_retrievers_00_009_sampled_50_queries_gpt-4-1106-preview_20231211_shuffled_qrel.txt", header=None, index=False, sep=" ")

### Prepare BM25 results in run format

In [159]:
bm25_df = pd.read_csv(BM25, sep="\t")

In [162]:
bm25_df.groupby('query').count()

passagem-id  \
query                                                                                                                      
As primaveiras estão sendo antessipadas?                                                                              10   
Brasileiros conseguem trabalhar em Portugal?                                                                          10   
Carne de capivara é saborosa?                                                                                         10   
Como José Sarney se tornou presidente do Brasil?                                                                      10   
Como a cultura por influenciar o pensamento de uma geração?                                                           10   
Como a técnica de normalização ajudam pacientes psicóticos?                                                           10   
Como baixar arquivos do OneDrive?                                                                                     10   
Como configurar uma linguagem do teclado windowns 10?                                                                 10   
Como definir a missão de uma empresa?                                                                                 10   
Como deixar a internet rápida?                                                                                        10   
Como desenvolveu-se a expansão portuguesa no continente Africano?                                                     10   
Como evitar edema labial?                                                                                             10   
Como fazer um risoto de camarão?                                                                                      10   
Como foi a ocupação do centro oeste brasileiro?                                                                       10   
Como idealizar uma nova constituição que seja mais realista que a nossa?                                              10   
Como o Brasil reagiu a epidemia de AIDS no fim do século XX?                                                          10   
Como obter o visto EB-5?                                                                                              10   
Como podemos classificar o relevo brasileiro?                                                                         10   
Como recorrer a uma multa indevida no DETRAN?                                                                         10   
Como se aplica o Ipratrópio?                                                                                          10   
Como se tornar um país melhor, autosuficiente e reduzir os impostos?                                                  10   
Como transformar uma cidade pacata em um polo turístico?                                                              10   
Como vencer os altos índices de inflação?                                                                             10   
Como é gerado um código SWIFT?                                                                                        10   
Consumo de leite e derivados está caindo?                                                                             10   
Crianças de quantos anos são exigidas autorização de viagem nacional?                                                 10   
Cuidados ao usar materiais perfurocortantes                                                                           10   
Custo de vida nos centros urbanos                                                                                     10   
Câmera Minja speed Dome não para de girar, o que pode ser?                                                            10   
Delirio versus alucinação                                                                                             10   
Dentro do contexto da depressão, como a psicose se manisfeta?                                                         10   
Dicas de escolha 

In [164]:
queries_01 = pd.read_csv("../trabalho_final/validation_queries_retrievals/queries_validation.tsv", sep='\t', header=None, names=['query_id', 'query'])
queries_02 = pd.read_csv("../trabalho_final/validation_queries_retrievals/validation_queries_mirelle.tsv", sep='\t', header=None, names=['query_id', 'query'])

In [165]:
queries_01.head()

query_id                                                             query
0         0                  Qual a maior característica da flora brasileira?
1         1                  Qual a maior característica da fauna brasileira?
2         2  Por que os países Guiana e Suriname não são filiados a Conmebol?
3         3                              Por que a Bolívia tem duas capitais?
4         4                             Qual o que significa decolonialidade?

In [166]:
queries_02.head()

query_id  \
0       100   
1       101   
2       102   
3       103   
4       104   

                                                                      query  
0                                             Qual objetivo da Enel Brasil?  
1                Qual a abordagem de mineração da moeda digital Chia (XCH)?  
2                 Quais produtos são revendidos pela empresa Casa da Coifa?  
3  Em que ano surgiu a Universities and Colleges Admissions Service (UCAS)?  
4    Quais etapas para a inscrição pelo Colleges Admissions Service (UCAS)?

In [170]:
all_queries_df = pd.concat([queries_01, queries_02])

In [171]:
all_queries_df.shape

(200, 2)

In [174]:
bm25_df = bm25_df.merge(all_queries_df)

In [175]:
bm25_df

query  \
0                    Qual objetivo da Enel Brasil?   
1                    Qual objetivo da Enel Brasil?   
2                    Qual objetivo da Enel Brasil?   
3                    Qual objetivo da Enel Brasil?   
4                    Qual objetivo da Enel Brasil?   
...                                            ...   
1985  Quais são as principais religiões do Brasil?   
1986  Quais são as principais religiões do Brasil?   
1987  Quais são as principais religiões do Brasil?   
1988  Quais são as principais religiões do Brasil?   
1989  Quais são as principais religiões do Brasil?   

                       passagem-id  \
0      clueweb22-pt0001-44-18816_1   
1      clueweb22-pt0001-44-10630_6   
2      clueweb22-pt0001-05-18926_3   
3      clueweb22-pt0000-62-20856_1   
4      clueweb22-pt0000-23-07245_1   
...                            ...   
1985   clueweb22-pt0001-38-06381_2   
1986   clueweb22-pt0001-90-19755_1   
1987  clueweb22-pt0001-73-16135_18   
1988   clueweb22-pt0000-22-04996_3   
1989   clueweb22-pt0000-55-10250_1   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       passagem-by-BM25  \
0                                                Nos últimos anos, o atendimento ao cliente Enel, tem se aprimorado, com o objetivo de facilitar ainda mais a vida dos consumidores. Com isso, grande parte dos serviços de atendimento ao cliente Enel, podem ser realizados de maneira prática, por meio da internet. Através do aplicativo Enel- Que está disponível para download em aparelhos com Android ou IO Nas Redes Sociais – Como na página do Facebook (Enel clientes Brasil). Ou no Twitter (@ Enel clientes BR). Por meio do site- Na página da Enel, (www.enel.com.br/pt.html). O atendimento Enel ao cliente, pode ser feito por meio de um assistente virtual. Veja o vídeo: Outras formas de atendimento Além de poder receber o atendimento por meio dos canais online, você também pode obter atendimento nos Estados onde a Enel Brasil está presente. Por meio do telefone de atendimento Enel 0800, ou indo pessoalmente a uma loja de atendimento mais próxima da sua casa. Número 0800 para atendimento da Enel Pelo telefone de atendimento ao cliente da Enel, é possível esclarecer suas dúvidas e ainda relatar algum problema, entre outros serviços. Veja quais são os telefones da Enel atendimento ao cliente, aproveite para anotar o número da Enel em seu estado: Atendimento ao cliente Enel Ceará: 0800 285 0196   
1     A ouvidoria é um canal de segunda instância que tem o objetivo de ouvir e tentar resolver problemas/solicitações que os canais convencionais de atendimento não foram capazes de solucionar. Caso nem mesmo a ouvidoria da Enel seja capaz de resolver em até 15 dias sua manifestação, é indicado que você busque ajuda dos ór

In [176]:
bm25_df.to_csv("../trabalho_final/validation_queries_retrievals/200-queries-passagens-by-BM25-pt_v2_with_query_id.tsv")

In [177]:
bm25_df['Q0'] = "Q0"
bm25_df['comment'] = "BM25"

In [178]:
bm25_top_10_df = bm25_df.groupby('query_id').head(10).reset_index(drop=True)

In [179]:
bm25_top_10_df.shape

(1990, 6)

In [181]:
bm25_top_10_df['position'] = np.tile(list(range(1, 11)), 199)
bm25_top_10_df['score'] = np.tile(list(range(100, 0, -10)), 199)

In [182]:
bm25_top_10_df.head(12)

query  \
0                                Qual objetivo da Enel Brasil?   
1                                Qual objetivo da Enel Brasil?   
2                                Qual objetivo da Enel Brasil?   
3                                Qual objetivo da Enel Brasil?   
4                                Qual objetivo da Enel Brasil?   
5                                Qual objetivo da Enel Brasil?   
6                                Qual objetivo da Enel Brasil?   
7                                Qual objetivo da Enel Brasil?   
8                                Qual objetivo da Enel Brasil?   
9                                Qual objetivo da Enel Brasil?   
10  Qual a abordagem de mineração da moeda digital Chia (XCH)?   
11  Qual a abordagem de mineração da moeda digital Chia (XCH)?   

                    passagem-id  \
0   clueweb22-pt0001-44-18816_1   
1   clueweb22-pt0001-44-10630_6   
2   clueweb22-pt0001-05-18926_3   
3   clueweb22-pt0000-62-20856_1   
4   clueweb22-pt0000-23-07245_1   
5   clueweb22-pt0000-39-18411_1   
6   clueweb22-pt0000-53-01312_1   
7   clueweb22-pt0000-83-02812_1   
8   clueweb22-pt0000-95-04739_1   
9   clueweb22-pt0001-00-02439_1   
10  clueweb22-pt0000-69-10254_1   
11  clueweb22-pt0001-99-11281_1   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     passagem-by-BM25  \
0                                              Nos últimos anos, o atendimento ao cliente Enel, tem se aprimorado, com o objetivo de facilitar ainda mais a vida dos consumidores. Com isso, grande parte dos serviços de atendimento ao cliente Enel, podem ser realizados de maneira prática, por meio da internet. Através do aplicativo Enel- Que está disponível para download em aparelhos com Android ou IO Nas Redes Sociais – Como na página do Facebook (Enel clientes Brasil). Ou no Twitter (@ Enel clientes BR). Por meio do site- Na página da Enel, (www.enel.com.br/pt.html). O atendimento Enel ao cliente, pode ser feito por meio de um assistente virtual. Veja o vídeo: Outras formas de atendimento Além de poder receber o atendimento por meio dos canais online, você também pode obter atendimento nos Estados onde a Enel Brasil está presente. Por meio do telefone de atendimento Enel 0800, ou indo pessoalmente a uma loja de atendimento mais próxima da sua casa. Número 0800 para atendimento da Enel Pelo telefone de atendimento ao cliente da Enel, é possível esclarecer suas dúvidas e ainda relatar algum problema, entre outros serviços. Veja quais são os telefones da Enel atendimento ao cliente, aproveite para anotar o número da Enel em seu estado: Atendimento ao cliente Enel Ceará: 0800 285 0196   
1   A ouvidoria é um canal de segunda instância que tem o objetivo de ouvir e tentar resolver problemas/solicitações que os canais c

In [184]:
bm25_top_10_df[['query_id', 'Q0', "passagem-id", "position", "score", "comment"]].to_csv("tests/200-queries-passagens-by-BM25-pt_v2_with_query_id_run.txt", header=None, index=False, sep=" ")

In [236]:
bm25_top_10_df.columns

Index(['query', 'passagem-id', 'passagem-by-BM25', 'query_id', 'Q0', 'comment',
       'position', 'score'],
      dtype='object')

In [237]:
bm25_top_10_df.columns = ['query', 'passage_id', 'passage', 'query_id', 'Q0', 'comment', 'position', 'score']

In [241]:
bm25_top_10_df[['query', 'passage_id', 'passage', 'query_id', 'score']].to_csv("tests/200-queries-passagens-by-BM25-pt_v2_with_query_id_for_evaluation.tsv", index=False, sep='\t')

(1990, 8)

#### Compute NDCG@10

In [219]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    tests/evaluation_04_retrievers_00_009_sampled_50_queries_gpt-4-1106-preview_20231211_qrel.txt tests/200-queries-passagens-by-BM25-pt_v2_with_query_id_run.txt

In [220]:
retrievers_results.append({'retriever':'BM25', 'nDCG@10': result[0].split('\t')[-1]})

### Prepare BM25 + E5 retrieval results in run format

In [71]:
bm25_e5_df = pd.read_csv(BM25_E5, sep="\t")

In [72]:
bm25_e5_df.groupby("query_id").head(10).count()

query          500
passage_id     500
score          500
query_id       500
colbertx_id    500
passage        500
dtype: int64

In [73]:
bm25_e5_run_df = bm25_e5_df.sort_values(["query_id", "score"], ascending=[True, False]).groupby("query_id").head(10)

In [74]:
bm25_e5_run_df.shape

(500, 6)

In [75]:
bm25_e5_run_df.head()

query  \
45085  Qual a maior característica da fauna brasileira?   
45086  Qual a maior característica da fauna brasileira?   
25257  Qual a maior característica da fauna brasileira?   
45087  Qual a maior característica da fauna brasileira?   
5097   Qual a maior característica da fauna brasileira?   

                        passage_id      score  query_id  colbertx_id  \
45085  clueweb22-pt0001-22-15255_0  88.380936         1      5877599   
45086  clueweb22-pt0000-96-00412_0  85.875961         1      4583617   
25257  clueweb22-pt0001-53-03652_0  85.536163         1      7347298   
45087  clueweb22-pt0001-22-15255_2  85.465218         1      5877601   
5097   clueweb22-pt0000-12-16721_0  85.453239         1       621398   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         passage  
45085                                                                                                                                  Fauna do Brasil - Toda Matéria Biologia › Zoologia Fauna do Brasil A fauna do Brasil é provavelmente a que possui a maior diversidade em espécies de animais vertebrados, anfíbios e primatas do globo terrestre. Existem três vezes mais espécies de peixes de água doce no Brasil do que em qualquer lugar no mundo. As aves também são muito variadas, colocando o Brasil como o país com a maior variedade de espécies na América do Sul e o terceiro do mundo em espécies de mamíferos. De igual modo, a Floresta Atlântica está entre as cinco regiões do planeta com mais espécies nativas, das quais 17% são aves e 10% são anfíbios e mamíferos encontrados somente na fauna brasileira. Vale citar que os animais da fauna brasileira são, via de regra, de pequeno porte. A importância científica da fauna brasileira é indescritível, pois contém a maior biodiversidade do mundo (cerca de 100 mil espécies de invertebrados, 8200 espécies vertebrados (713 mamíferos, 1826 aves, 721 répteis, 875 anfíbios, 2800 peixes continentais e 1300 peixes marinhos) das quais 627 já estão na lista negra das espécies ameaçadas de extinção (394 espécies terrestres e 233 espécies aquáticas).  
45086  15 ANIMAIS BRASILEIROS: Características e curiosidades Animais brasileiros: nativos, endêmicos e em risco de extinção Fauna quer dizer o conjunto de espécies que vivem em uma determinada região. Por isso, é importante saber diferenciar que quando falamos sobre a fauna brasileira, estamos falando sobre todas as espécies que habitam o Brasil, mas não necessariamente apenas de espécies endêmicas ou nativas, já que alguns animais são considerados espécies invasoras e/ou foram introduzidos pela pessoa humana. Para te mostrar um pouco da nossa incrível fauna, neste post do PeritoAnimal nos focamos em listar aqueles animais brasileiros: nativos e endêmicos

In [76]:
bm25_e5_run_df['Q0'] = "Q0"

In [77]:
bm25_e5_run_df['comment'] = "gpt-4-1106-preview"

In [115]:
bm25_e5_run_df['index'] = np.tile(list(range(1, 11)), 50)

In [116]:
bm25_e5_run_df.head(12)

query  \
45085                  Qual a maior característica da fauna brasileira?   
45086                  Qual a maior característica da fauna brasileira?   
25257                  Qual a maior característica da fauna brasileira?   
45087                  Qual a maior característica da fauna brasileira?   
5097                   Qual a maior característica da fauna brasileira?   
15136                  Qual a maior característica da fauna brasileira?   
5098                   Qual a maior característica da fauna brasileira?   
25258                  Qual a maior característica da fauna brasileira?   
25259                  Qual a maior característica da fauna brasileira?   
35109                  Qual a maior característica da fauna brasileira?   
15364  Por que os países Guiana e Suriname não são filiados a Conmebol?   
15365  Por que os países Guiana e Suriname não são filiados a Conmebol?   

                         passage_id      score  query_id  colbertx_id  \
45085   clueweb22-pt0001-22-15255_0  88.380936         1      5877599   
45086   clueweb22-pt0000-96-00412_0  85.875961         1      4583617   
25257   clueweb22-pt0001-53-03652_0  85.536163         1      7347298   
45087   clueweb22-pt0001-22-15255_2  85.465218         1      5877601   
5097    clueweb22-pt0000-12-16721_0  85.453239         1       621398   
15136  clueweb22-pt0001-79-01222_35  85.312119         1      8525784   
5098   clueweb22-pt0000-41-09016_12  85.252022         1      1985606   
25258   clueweb22-pt0001-66-11652_2  84.958542         1      7987527   
25259   clueweb22-pt0001-65-01422_4  84.874046         1      7919568   
35109   clueweb22-pt0000-71-21314_0  84.854614         1      3434451   
15364   clueweb22-pt0001-73-10674_5  86.986504         2      8315740   
15365   clueweb22-pt0001-73-10674_1  86.646065         2      8315737   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            passage  \
45085                                                                                                                                                                                                     Fauna do Brasil - Toda Matéria Biologia › Zoologia Fauna do Brasil A fauna do Brasil é provavelmente a que possui a maior diversidade em espécies de animais vertebrados, anfíbios e primatas do globo terrestre. Existem três vezes mais espécies de peixes de água doce no Brasil do que em qualquer lugar no mundo. As aves também são muito variadas, colocando o Brasil como o país com a maior variedade de espécies na América do Sul e o terceiro do mundo em espécies de mamíferos. De igual modo, a Floresta Atlântica está entre as cinco regiões do planeta com mais espécies n

In [81]:
bm25_e5_run_df[['query_id', 'Q0', "passage_id", "index", "score", "comment"]].to_csv("tests/bm25_e5_docs_000_999_50_sampled_queries_run.txt", header=None, index=False, sep=" ")

#### Compute NDCG@10

In [221]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    tests/evaluation_04_retrievers_00_009_sampled_50_queries_gpt-4-1106-preview_20231211_qrel.txt tests/bm25_e5_docs_000_999_50_sampled_queries_run.txt

In [222]:
retrievers_results.append({'retriever':'BM25+E5', 'nDCG@10': result[0].split('\t')[-1]})

In [102]:
!/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    tests/evaluation_04_retrievers_00_009_sampled_50_queries_gpt-4-1106-preview_20231211_shuffled_qrel.txt tests/bm25_e5_docs_000_999_50_sampled_queries_run.txt

ndcg_cut_10           	all	0.6820


### Prepare BM25 + mT5 results in run format

In [40]:
mt5_df = pd.read_csv(BM25_MT5, sep="\t")

In [41]:
mt5_df

query  \
0                         Qual objetivo da Enel Brasil?   
1                         Qual objetivo da Enel Brasil?   
2                         Qual objetivo da Enel Brasil?   
3                         Qual objetivo da Enel Brasil?   
4                         Qual objetivo da Enel Brasil?   
...                                                 ...   
199995  Que receitas eu posso fazer com 5 ingredientes?   
199996  Que receitas eu posso fazer com 5 ingredientes?   
199997  Que receitas eu posso fazer com 5 ingredientes?   
199998  Que receitas eu posso fazer com 5 ingredientes?   
199999  Que receitas eu posso fazer com 5 ingredientes?   

                              doc_id  \
0        clueweb22-pt0000-58-10513_2   
1        clueweb22-pt0000-81-12555_1   
2        clueweb22-pt0000-39-18411_1   
3        clueweb22-pt0002-00-04601_1   
4        clueweb22-pt0000-58-10513_0   
...                              ...   
199995  clueweb22-pt0001-20-08083_10   
199996   clueweb22-pt0000-12-13275_2   
199997   clueweb22-pt0000-00-21229_1   
199998   clueweb22-pt0000-37-04796_7   
199999  clueweb22-pt0001-84-06499_18   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                passage-by-bm25-mt5  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Sendo assim, em linha com o modelo de Criação de Valor Compartilhado (Creating Shared Value - CSV) adotado pela companhia mundialmente, temos o objetivo de associar o desenvolvimento do nosso negócio às necessidades das comunidades brasileiras e realizamos diversas iniciativas para possibilitar a geração de renda, como cursos, oficinas e outros projetos sociais. Além disso, nos comprometemos explicitamente a alcançar quatro dos 17 Objetivos de Desenvolvimento Sustentável (ODS) da ONU: amplo acesso à energia limpa e acessível, apoio à educação de qualidade, contribuição para o desenvolvimento socioeconômico e combate contra as alterações climáticas. Conheça o novo site da Enel Brasil Selecione o seu Estado: RIO DE JANEIRO CEARÁ GOIÁS SÃO PAULO Não é cliente Enel? Clique aqui e conheça o nosso Grupo   
1       A Enel Brasil foi constituída em 2005 com o objeto de centralizar as participações societárias do grupo Enel no país e criar, por meio de uma holding de empresas, uma plataforma sólida de gestão dos ativos que preparasse a companhia para futuras expansões. Em 2007, a Enel SpA, 

In [134]:
mt5_df.groupby('query_id').count()

query  doc_id  passage-by-bm25-mt5
query_id                                    
0          1000    1000                 1000
1          1000    1000                 1000
2          1000    1000                 1000
3          1000    1000                 1000
4          1000    1000                 1000
5          1000    1000                 1000
6          1000    1000                 1000
7          1000    1000                 1000
8          1000    1000                 1000
9          1000    1000                 1000
10         1000    1000                 1000
11         1000    1000                 1000
12         1000    1000                 1000
13         1000    1000                 1000
14         1000    1000                 1000
15         1000    1000                 1000
16         1000    1000                 1000
17         1000    1000                 1000
18         1000    1000                 1000
19         1000    1000                 1000
20         1000    1000                 1000
21         1000    1000                 1000
22         1000    1000                 1000
23         1000    1000                 1000
24         1000    1000                 1000
25         1000    1000                 1000
26         1000    1000                 1000
27         1000    1000                 1000
28         1000    1000                 1000
29         1000    1000                 1000
30         1000    1000                 1000
31         1000    1000                 1000
32         1000    1000                 1000
33         1000    1000                 1000
34         1000    1000                 1000
35         1000    1000                 1000
36         1000    1000                 1000
37         1000    1000                 1000
38         1000    1000                 1000
39         1000    1000                 1000
40         1000    1000                 1000
41         1000    1000                 1000
42         1000    1000                 1000
43         1000    1000                 1000
44         1000    1000                 1000
45         1000    1000                 1000
46         1000    1000                 1000
47         1000    1000                 1000
48         1000    1000                 1000
49         1000    1000                 1000
50         1000    1000                 1000
51         1000    1000                 1000
52         1000    1000                 1000
53         1000    1000                 1000
54         1000    1000                 1000
55         1000    1000                 1000
56         1000    1000                 1000
57         1000    1000                 1000
58         1000    1000                 1000
59         1000    1000                 1000
60         1000    1000                 1000
61         1000    1000                 1000
62         1000    1000                 1000
63         1000    1000                 1000
64         1000    1000                 1000
65         1000    1000                 1000
66         1000    1000                 1000
67         1000    1000                 1000
68         1000    1000                 1000
69         1000    1000                 1000
70         1000    1000                 1000
71         1000    1000                 1000
72         1000    1000                 1000
73         1000    1000                 1000
74         1000    1000                 1000
75         1000    1000                 1000
76         1000    1000                 1000
77         1000    1000                 1000
78         1000    1000                 1000
79         1000    1000                 1000
80         1000    1000                 1000
81         1000    1000                 1000
82         1000    1000                 1000
83         1000    1000                 1000
84         1000    1000                 1000
85         1000    1000                 1000
86         1000    1000                 1000
87   

In [133]:
mt5_df.drop_duplicates('query_id')[['query_id', 'query']]

query_id  \
0            100   
1000         101   
2000         102   
3000         103   
4000         104   
5000         105   
6000         106   
7000         107   
8000         108   
9000         109   
10000        110   
11000        111   
12000        112   
13000        113   
14000        114   
15000        115   
16000        116   
17000        117   
18000        118   
19000        119   
20000        120   
21000        121   
22000        122   
23000        123   
24000        124   
25000        125   
26000        126   
27000        127   
28000        128   
29000        129   
30000        130   
31000        131   
32000        132   
33000        133   
34000        134   
35000        135   
36000        136   
37000        137   
38000        138   
39000        139   
40000        140   
41000        141   
42000        142   
43000        143   
44000        144   
45000        145   
46000        146   
47000        147   
48000        148   
49000        149   
50000        150   
51000        151   
52000        152   
53000        153   
54000        154   
55000        155   
56000        156   
57000        157   
58000        158   
59000        159   
60000        160   
61000        161   
62000        162   
63000        163   
64000        164   
65000        165   
66000        166   
67000        167   
68000        168   
69000        169   
70000        170   
71000        171   
72000        172   
73000        173   
74000        174   
75000        175   
76000        176   
77000        177   
78000        178   
79000        179   
80000        180   
81000        181   
82000        182   
83000        183   
84000        184   
85000        185   
86000        186   
87000        187   
88000        188   
89000        189   
90000        190   
91000        191   
92000        192   
93000        193   
94000        194   
95000        195   
96000        196   
97000        197   
98000        198   
99000        199   
100000         1   
101000         2   
102000         3   
103000         4   
104000         5   
105000         6   
106000         7   
107000         8   
108000         9   
109000        10   
110000        11   
111000        12   
112000        13   
113000        14   
114000        15   
115000        16   
116000        17   
117000        18   
118000        19   
119000        20   
120000        21   
121000        22   
122000        23   
123000        24   
124000        25   
125000        26   
126000        27   
127000        28   
128000        29   
129000        30   
130000        31   
131000        40   
132000        41   
133000        42   
134000        43   
135000        44   
136000        45   
137000        46   
138000        47   
139000        48   
140000        49   
141000        50   
142000        51   
143000        52   
144000        53   
145000        54   
146000        55   
147000        56   
148000        57   
149000        58   
150000        59   
151000        60   
152000        61   
153000        62   
154000        63   
155000        64   
156000        65   
157000        66   
158000        67   
159000        68   
160000        69   
161000        70   
162000        71   
163000        72   
164000        73   
165000        74   
166000        75   
167000        76   
168000        77   
169000        78   
170000        79   
171000        80   
172000        81   
173000        82   
174000        83   
175000        84   
176000        85   
177000        86   
178000        87   
179000        88   
180000        89   
181000        90   
182000        91   
183000        92   
184000        93   
185000        94   
186000        95   
187000        96   
188000        97   
189000        98   
190000        99   
191000        36   
192000        37   
193000        32   
194000        34   
195000        39   
196000        35   
197000        33   
198000         0   
199000  

In [135]:
mt5_df['Q0'] = "Q0"
mt5_df['comment'] = "BM25+mT5"

In [145]:
mt5_top_10_df = mt5_df.groupby('query_id').head(10).reset_index(drop=True)

In [146]:
mt5_top_10_df.shape

(2000, 6)

In [147]:
mt5_top_10_df['position'] = np.tile(list(range(1, 11)), 200)

In [149]:
mt5_top_10_df['score'] = np.tile(list(range(100, 0, -10)), 200)

In [150]:
mt5_top_10_df.head(12)

query  \
0                                Qual objetivo da Enel Brasil?   
1                                Qual objetivo da Enel Brasil?   
2                                Qual objetivo da Enel Brasil?   
3                                Qual objetivo da Enel Brasil?   
4                                Qual objetivo da Enel Brasil?   
5                                Qual objetivo da Enel Brasil?   
6                                Qual objetivo da Enel Brasil?   
7                                Qual objetivo da Enel Brasil?   
8                                Qual objetivo da Enel Brasil?   
9                                Qual objetivo da Enel Brasil?   
10  Qual a abordagem de mineração da moeda digital Chia (XCH)?   
11  Qual a abordagem de mineração da moeda digital Chia (XCH)?   

                          doc_id  \
0    clueweb22-pt0000-58-10513_2   
1    clueweb22-pt0000-81-12555_1   
2    clueweb22-pt0000-39-18411_1   
3    clueweb22-pt0002-00-04601_1   
4    clueweb22-pt0000-58-10513_0   
5    clueweb22-pt0001-87-07358_1   
6    clueweb22-pt0001-13-07592_1   
7    clueweb22-pt0001-64-11884_1   
8    clueweb22-pt0000-23-07245_1   
9   clueweb22-pt0000-74-07553_14   
10   clueweb22-pt0000-69-10254_1   
11   clueweb22-pt0000-34-04557_4   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            passage-by-bm25-mt5  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Sendo assim, em linha com o modelo de Criação de Valor Compartilhado (Creating Shared Value - CSV) adotado pela companhia mundialmente, temos o objetivo de associar o desenvolvimento do nosso negócio às necessidades das comunidades brasileiras e realizamos diversas iniciativas para possibilitar a geração de renda, como cursos, oficinas e outros projetos sociais. Além disso, nos comprometemos explicitamente a alcançar quatro dos 17 Objetivos de Desenvolvimento Sustentável (ODS) da ONU: amplo acesso à energia limpa e acessível, apoio à educação de qualidade, contribuição para o desenvolvimento socioeconômico e combate contra as alterações climáticas. Conheça o novo site da Enel Brasil Selecione o seu Estado: RIO DE JANEIRO CEARÁ GOIÁS SÃO PAULO Não é cliente Enel? Clique aqui e conheça o nosso Grupo   
1   A Enel Brasil foi constituída em 2005 com o objeto de centralizar as participações societárias do grupo Enel no país e criar, por meio de uma holding de empres

In [151]:
mt5_top_10_df[['query_id', 'Q0', "doc_id", "position", "score", "comment"]].to_csv("tests/200-queries-passagens-by-BM25-mT5_v4_with_query_id_run.txt", header=None, index=False, sep=" ")

#### Compute NDCG@10

In [223]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    tests/evaluation_04_retrievers_00_009_sampled_50_queries_gpt-4-1106-preview_20231211_qrel.txt tests/200-queries-passagens-by-BM25-mT5_v4_with_query_id_run.txt

In [224]:
retrievers_results.append({'retriever':'BM25+mT5', 'nDCG@10': result[0].split('\t')[-1]})

### Prepare SPLADE results in run format

In [140]:
splade_df = pd.read_csv(SPLADE, sep="\t")

In [141]:
splade_df

query_id  Q0  colbertx_id  position      score    comment  \
0              0  Q0      6124160         1  18.215471  SPLADE-PT   
1              0  Q0      9394964         2  18.258245  SPLADE-PT   
2              1  Q0      9394964       706  18.854155  SPLADE-PT   
3             68  Q0      9394964       921  18.207718  SPLADE-PT   
4              0  Q0       319340         3  17.736769  SPLADE-PT   
...          ...  ..          ...       ...        ...        ...   
199995       199  Q0      6138175       995  12.434690  SPLADE-PT   
199996       199  Q0      3132292       996  12.457484  SPLADE-PT   
199997       199  Q0      1040828       997  12.447216  SPLADE-PT   
199998       199  Q0      5391434       999  12.460681  SPLADE-PT   
199999       199  Q0      4831616      1000  12.433900  SPLADE-PT   

                          clueweb_id  
0        clueweb22-pt0001-27-16321_1  
1        clueweb22-pt0001-97-01569_0  
2        clueweb22-pt0001-97-01569_0  
3        clueweb22-pt0001-97-01569_0  
4        clueweb22-pt0000-06-04821_0  
...                              ...  
199995   clueweb22-pt0001-28-00764_1  
199996   clueweb22-pt0000-65-16234_4  
199997   clueweb22-pt0000-21-11900_3  
199998   clueweb22-pt0001-12-09424_3  
199999  clueweb22-pt0001-01-01457_10  

[200000 rows x 7 columns]

In [142]:
splade_sorted_df = splade_df.sort_values(["query_id", "score"], ascending=[True, False]).groupby('query_id').head(10)

In [143]:
splade_sorted_df

query_id  Q0  colbertx_id  position      score    comment  \
802            0  Q0      4178525       360  22.945511  SPLADE-PT   
625            0  Q0      7135402       280  22.692141  SPLADE-PT   
11             0  Q0      5539594         6  22.510916  SPLADE-PT   
278            0  Q0      6946573       122  22.492905  SPLADE-PT   
841            0  Q0      5977156       382  22.464260  SPLADE-PT   
...          ...  ..          ...       ...        ...        ...   
198667       199  Q0      1827001        70  23.841969  SPLADE-PT   
198569       199  Q0      2396198       641  23.648439  SPLADE-PT   
198507       199  Q0      4244278       687  23.571337  SPLADE-PT   
198511       199  Q0      8308524        11  23.179789  SPLADE-PT   
198467       199  Q0      3447310       167  23.114687  SPLADE-PT   

                           clueweb_id  
802       clueweb22-pt0000-87-14633_2  
625     clueweb22-pt0001-48-11769_116  
11        clueweb22-pt0001-15-15106_2  
278       clueweb22-pt0001-44-12879_4  
841       clueweb22-pt0001-24-16393_2  
...                               ...  
198667    clueweb22-pt0000-38-01029_7  
198569    clueweb22-pt0000-50-08513_1  
198507   clueweb22-pt0000-88-19545_11  
198511   clueweb22-pt0001-73-07268_17  
198467    clueweb22-pt0000-72-04342_0  

[2000 rows x 7 columns]

In [144]:
splade_sorted_df['position'] = np.tile(list(range(1, 11)), 200)

In [118]:
splade_sorted_df.head(12)

query_id  Q0  colbertx_id  position      score    comment  \
802          0  Q0      4178525         1  22.945511  SPLADE-PT   
625          0  Q0      7135402         2  22.692141  SPLADE-PT   
11           0  Q0      5539594         3  22.510916  SPLADE-PT   
278          0  Q0      6946573         4  22.492905  SPLADE-PT   
841          0  Q0      5977156         5  22.464260  SPLADE-PT   
1462         0  Q0      8000654         6  22.444901  SPLADE-PT   
588          0  Q0      9609753         7  22.388660  SPLADE-PT   
766          0  Q0       473093         8  22.112490  SPLADE-PT   
947          0  Q0      4077560         9  22.045551  SPLADE-PT   
489          0  Q0      4138910        10  21.752874  SPLADE-PT   
1202         1  Q0      5762187         1  23.876745  SPLADE-PT   
313          1  Q0       827050         2  22.891438  SPLADE-PT   

                         clueweb_id  
802     clueweb22-pt0000-87-14633_2  
625   clueweb22-pt0001-48-11769_116  
11      clueweb22-pt0001-15-15106_2  
278     clueweb22-pt0001-44-12879_4  
841     clueweb22-pt0001-24-16393_2  
1462    clueweb22-pt0001-67-00120_5  
588     clueweb22-pt0002-01-16686_0  
766     clueweb22-pt0000-09-13182_0  
947     clueweb22-pt0000-85-17244_5  
489    clueweb22-pt0000-86-19982_33  
1202    clueweb22-pt0001-20-06522_1  
313     clueweb22-pt0000-17-01771_1

In [119]:
splade_sorted_df[['query_id', 'Q0', "clueweb_id", "position", "score", "comment"]].to_csv("tests/splade_pt_result_with_clueweb_id_run.txt", header=None, index=False, sep=" ")

#### Compute NDCG@10

In [225]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    tests/evaluation_04_retrievers_00_009_sampled_50_queries_gpt-4-1106-preview_20231211_qrel.txt tests/splade_pt_result_with_clueweb_id_run.txt

In [226]:
retrievers_results.append({'retriever':'SPLADE_pt-BR', 'nDCG@10': result[0].split('\t')[-1]})

### Prepare ColbertX results in run format

In [108]:
colbertx_df = pd.read_csv(COLBERTX, sep="\t")

In [109]:
colbertx_df

query_id  colbertx_id  doc_position  doc_score  score_znorm  part  \
0               0      4138910             1  28.797396     3.723518     2   
1               1      4138910             1  28.135212     3.365722     2   
2              25      4138910           671  21.382965    -0.282701     2   
3              26      4138910           476  20.872330    -0.558611     2   
4              54      4138910            31  26.231224     2.336945     2   
...           ...          ...           ...        ...          ...   ...   
3193552       199      7325692           722  19.289238    -1.382245     3   
3193553       199      6825557           723  19.273064    -1.391039     3   
3193554       199      6358548           654  19.174335    -1.444718     3   
3193555       199      2829893           648  19.097916    -1.486261     1   
3193556       199      6762245           724  18.672707    -1.717458     3   

                            clueweb_id  
0         clueweb22-pt0000-86-19982_33  
1         clueweb22-pt0000-86-19982_33  
2         clueweb22-pt0000-86-19982_33  
3         clueweb22-pt0000-86-19982_33  
4         clueweb22-pt0000-86-19982_33  
...                                ...  
3193552  clueweb22-pt0001-52-15266_355  
3193553    clueweb22-pt0001-42-02150_2  
3193554    clueweb22-pt0001-32-16864_1  
3193555  clueweb22-pt0000-59-19225_192  
3193556    clueweb22-pt0001-40-18590_0  

[3193557 rows x 7 columns]

In [124]:
colbertx_sorted_df = colbertx_df.sort_values(["query_id", "score_znorm"], ascending=[True, False]).groupby('query_id').head(10)

In [125]:
colbertx_sorted_df.shape

(2000, 7)

In [126]:
colbertx_sorted_df['doc_position'] = np.tile(list(range(1, 11)), 200)

In [128]:
colbertx_sorted_df['Q0'] = 'Q0'

In [129]:
colbertx_sorted_df['comment'] = 'colbertx'

In [127]:
colbertx_sorted_df.head(12)

query_id  colbertx_id  doc_position  doc_score  score_znorm  part  \
0           0      4138910             1  28.797396     3.723518     2   
7           0      8157162             2  28.422802     3.516794     4   
17          0      7828446             3  28.384157     3.495905     3   
23          0      3392707             4  28.252335     3.415572     1   
31          0      2325385             5  28.157360     3.364606     1   
39          0      8430956             6  28.131063     3.359750     4   
44          0      6865798             7  28.121971     3.355167     3   
52          0      3577057             8  28.106983     3.337572     1   
70          0      3917442             9  28.045986     3.304839     1   
81          0      7987527            10  28.024965     3.303096     3   
8           1      8157162             1  28.392147     3.500292     4   
184         1      5877599             2  28.366890     3.490904     2   

                       clueweb_id  
0    clueweb22-pt0000-86-19982_33  
7     clueweb22-pt0001-70-06195_8  
17    clueweb22-pt0001-63-03254_3  
23    clueweb22-pt0000-71-04006_2  
31    clueweb22-pt0000-48-18850_1  
39    clueweb22-pt0001-76-07787_4  
44   clueweb22-pt0001-42-18761_18  
52    clueweb22-pt0000-75-07965_7  
70    clueweb22-pt0000-82-13187_0  
81    clueweb22-pt0001-66-11652_2  
8     clueweb22-pt0001-70-06195_8  
184   clueweb22-pt0001-22-15255_0

In [130]:
colbertx_sorted_df[['query_id', 'Q0', "clueweb_id", "doc_position", "score_znorm", "comment"]].to_csv("tests/colbertx_all_znormalized_validation_scores_000_199_run.txt", header=None, index=False, sep=" ")

#### Compute NDCG@10

In [227]:
result = !/media/eduseiti/bigdata01/unicamp/ia368v_dd/pyserini/tools/eval/trec_eval.9.0.4/trec_eval -c -mndcg_cut.10 \
    tests/evaluation_04_retrievers_00_009_sampled_50_queries_gpt-4-1106-preview_20231211_qrel.txt tests/colbertx_all_znormalized_validation_scores_000_199_run.txt

In [228]:
retrievers_results.append({'retriever':'ColBERT-X_mMARCO_pt-BR', 'nDCG@10': result[0].split('\t')[-1]})

### Check the overall results

In [229]:
pd.DataFrame(retrievers_results)

retriever nDCG@10
0                    BM25  0.2967
1                 BM25+E5  0.6820
2                BM25+mT5  0.7597
3            SPLADE_pt-BR  0.6119
4  ColBERT-X_mMARCO_pt-BR  0.6649

### Check execution log against BM25 retrievals

In [230]:
import pickle

In [231]:
with open("tests/execution_rev_2.1_sampled_50_queries_gpt-4-1106-preview_20231211.pkl", "rb") as input_file:
    logs = pickle.load(input_file)

In [233]:
already_analized = 0

for i, row in bm25_top_10_df.iterrows():
    if (row['query'] + "_" + row['passagem-id']) in logs['evaluation_cache']:
        print("Already analized...")

        already_analized += 1

Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...


In [234]:
already_analized 

181

In [235]:
already_analized / bm25_top_10_df.shape[0]

0.09095477386934674

#### Filter the sampled 50 queries for GPT-4 evaluation

In [242]:
bm25_eval_df = pd.read_csv("tests/200-queries-passagens-by-BM25-pt_v2_with_query_id_for_evaluation.tsv", sep='\t')

In [243]:
bm25_eval_df

query  \
0                    Qual objetivo da Enel Brasil?   
1                    Qual objetivo da Enel Brasil?   
2                    Qual objetivo da Enel Brasil?   
3                    Qual objetivo da Enel Brasil?   
4                    Qual objetivo da Enel Brasil?   
...                                            ...   
1985  Quais são as principais religiões do Brasil?   
1986  Quais são as principais religiões do Brasil?   
1987  Quais são as principais religiões do Brasil?   
1988  Quais são as principais religiões do Brasil?   
1989  Quais são as principais religiões do Brasil?   

                        passage_id  \
0      clueweb22-pt0001-44-18816_1   
1      clueweb22-pt0001-44-10630_6   
2      clueweb22-pt0001-05-18926_3   
3      clueweb22-pt0000-62-20856_1   
4      clueweb22-pt0000-23-07245_1   
...                            ...   
1985   clueweb22-pt0001-38-06381_2   
1986   clueweb22-pt0001-90-19755_1   
1987  clueweb22-pt0001-73-16135_18   
1988   clueweb22-pt0000-22-04996_3   
1989   clueweb22-pt0000-55-10250_1   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                passage  \
0                                                Nos últimos anos, o atendimento ao cliente Enel, tem se aprimorado, com o objetivo de facilitar ainda mais a vida dos consumidores. Com isso, grande parte dos serviços de atendimento ao cliente Enel, podem ser realizados de maneira prática, por meio da internet. Através do aplicativo Enel- Que está disponível para download em aparelhos com Android ou IO Nas Redes Sociais – Como na página do Facebook (Enel clientes Brasil). Ou no Twitter (@ Enel clientes BR). Por meio do site- Na página da Enel, (www.enel.com.br/pt.html). O atendimento Enel ao cliente, pode ser feito por meio de um assistente virtual. Veja o vídeo: Outras formas de atendimento Além de poder receber o atendimento por meio dos canais online, você também pode obter atendimento nos Estados onde a Enel Brasil está presente. Por meio do telefone de atendimento Enel 0800, ou indo pessoalmente a uma loja de atendimento mais próxima da sua casa. Número 0800 para atendimento da Enel Pelo telefone de atendimento ao cliente da Enel, é possível esclarecer suas dúvidas e ainda relatar algum problema, entre outros serviços. Veja quais são os telefones da Enel atendimento ao cliente, aproveite para anotar o número da Enel em seu estado: Atendimento ao cliente Enel Ceará: 0800 285 0196   
1     A ouvidoria é um canal de segunda instância que tem o objetivo de ouvir e tentar resolver problemas/solicitações que os canais convencionais de atendimento não foram capazes de solucionar. Caso nem mesmo a ouvidoria da Enel seja capaz de resolver em até 15 dias sua manifestação, é indicado que você busque ajuda dos ór

In [244]:
sampled_queries_df = pd.read_csv("../trabalho_final/final_validation_queries/50-dataset-doccano-queries-passagens-by-BM25-mT5_with_query_id.tsv", sep="\t")

In [245]:
sampled_queries_df.shape

(500, 5)

In [246]:
sampled_queries_list_df = sampled_queries_df.drop_duplicates('query')[['query_id', 'query']].reset_index(drop=True)

In [247]:
bm25_eval_df = bm25_eval_df.merge(sampled_queries_list_df, left_on="query", right_on="query")

In [249]:
bm25_eval_df.shape

(500, 6)

In [251]:
already_analized = 0

for i, row in bm25_eval_df.iterrows():
    if (row['query'] + "_" + row['passage_id']) in logs['evaluation_cache']:
        print("Already analized...")

        already_analized += 1

Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...
Already analized...


In [252]:
already_analized

181

In [253]:
already_analized / bm25_eval_df.shape[0]

0.362

In [254]:
bm25_eval_df.to_csv("tests/bm25_docs_000_009_50_sampled_queries.tsv", sep='\t', index=False)